In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
pd.set_option('display.max_columns', 1000)

In [2]:
from pyspark.sql.functions import sum as _sum
from pyspark.sql.functions import when, col, countDistinct, datediff, collect_set, ceil, lit, broadcast
import pyspark.sql.functions as F
from pyspark.sql.window import Window
from pyspark.sql.types import IntegerType, FloatType, StringType, DateType

In [4]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Split") \
    .config("spark.driver.memory", "10g") \
    .config("spark.executor.memory", "8g") \
    .getOrCreate()
spark.sparkContext.setLogLevel("ERROR")
spark.conf.set("spark.sql.shuffle.partitions", "400")
csv_file_path = "data/OASIS_v2.csv"
df = spark.read.csv(csv_file_path, header=True, inferSchema=True)

In [5]:
df.show(5)

+---------------+---------------+-------------------------+---------------------+--------------------+--------------------------+--------+---------------+--------------------+----------------------+------------+------------------------+------------------+--------------------------+-----------------------+-------------+----------------+------------------+------+--------------------------------+-----+-------------------------+------------------+----------------------------------+----------------------+-----+------------------------+-------------------------+-----------------------+-----------------------------+----------------------------------------------------------------+---------------------------------+--------------------------------+--------------------------------+---------------------------------+----------------------------------+---------------------------------------------------------+------------------------------------+--------------------------+-----------------------------------+------------------------------------+-----------------------------------+-----------------------------+----------------------------+--------------------------------------+----------------------+-----------------------------------+--------------------------------+----------------------------------+------------------------+------------------------+-------------------+------------------------+------+---------------+-------------------------------+--------------------------+----------------------+-------------------------------------------+-------------------------+----------------------------------+-----------------------------------------+--------------------------+----------------------------------------------+-----------------------------------------+-----------------------------------------+----------------------------------------+--------------------+--------------------------------------------+---------------------------------------+---------------------------------------+-----------------------------------------+-------------------------+------------------------+-----------------------------------+---------------------------+-----------------------------+---------------------------------+------------------------------------+-----------------------------------------+------------------------------------+----------------------------+----------------------------+---------------------+-------------+------------+--------------------+----------------------------------+-------------------------------------------+--------------------------------+---------------------------------------+------------------------------------+---------------------------------------+-----------------------------------------+------------------------------------+---------------------------------------+-----------------------------------------+-------------------------------+----------------+-------------------+-------------------+---------------+-------------------+-------------------------+------------+---------------------+---------------+-----------------------------+-----------------+-------------------------------------+------------------------------------------+------------------------------------+-----------------------------------+---------------------------------+-------------------------------------+--------------------------------------+-------------------------------------+-------------------------------------------+-------------------------------------+--------------------------------------------------+---------------+-----------------------------+---------------------------------------+--------------------------------+----------------------------------------+---------------------------------------+--------------------------------------+----------------------------------------------------+-----------------------------------------------+--------------------------------------------+----------------------------------------+---------------------------------------------+------------------------------------------+------------------------------+----------------------------------+--------------------------------+------------------------------------------------+------------------------------------------+------------------------------------------+------------------------------------------+----------------------------------------+----------------------------------------------+-------------------------------------+----------------------------+------------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------------+---------------------------------------------+---------------------------+---------------------+---------------------------------------+-----------------------------------+----------------------------------------+-------------------------------------+-------------------------+-----------------------------+----------------------------------+--------------------------------------------------+-------------------------------------+--------------------------------------------------+-------------------------------------+-----------------------------------+-----------------------------------------+--------------------------------+------------------------------+-------------------------------------+------------------------------------------------+---------------------------------+---------------------------------+------------------------------------+---------------------------------------------+--------------------------------+--------------------------------+--------------------------------+--------------------------------+--------------------------------+--------------------------------+---------------------------------------------+-------------------------------------+-------------------------------------+-------------------------------------+-------------------------------------+-------------------------------------+-------------------------------------+---------------------------------------------+---------------------------------+-------------------------------------------------+---------------------------------+------------------------------------------+---------------------------------+------------------------------------------+---------------------------------+------------------------------------------+---------------------------------+------------------------------------------+---------------------------------+------------------------------------------+------------------------------------------+----------------------------------------------------+------------------------------------+---------------------------------------------+------------------------------------+---------------------------------------------+------------------------------------+---------------------------------------------+------------------------------------+---------------------------------------------+------------------------------------+---------------------------------------------+-------------------------------------+------------------------------------+--------------------------------------------------+-------------------------------------------+----------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------+-----------------------------------+------------------------------+------------------------------------------+------------------------------+-------------------------------+-----------------------------------------+---------------------------------------------+---------------------------------------+--------------------------------------+----------------------------------------+---------------------------------------------+----------------------------------------+---------------------------------------------+-------------+----------------------------------+---------------------------+----------------+----------------+---------------------------------+--------------------------------------------+---------------------------------+--------------------------------------------+---------------------------------+--------------------------------------------+----------------------------------------+------------------------------------------------+--------------------------------------+----------------------------------------------+------------------------------------------+--------------------------------------------------+---------------------+---------------------+---------------------+----------------------------------------------+------------------------------------------------+--------------------------------------------+----------------------------------+-------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------------------+-------------------------------------------+-------------------+--------------------+-----------------------+---------------------------------------------+-------------------------------------------+----------------------------------------+---------------------------------------------+--------------------------------------+-----------------------------------------------+---------------------------------------------+----------------------------------------------+--------------+---------+-------------+-----------------+--------------------+--------------+---+------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
| Beneficiary_ID|  Assessment_ID|Assessment_Effective_Date|Calculated_HIPPS_Code|Facility_Internal_ID|HHA_Assessment_Internal_ID|State_ID|Submission_Date|Submitted_HIPPS_Code|Agency_Medicare_Number|Branch_State|Branch_Identifier_Number|Start_of_Care_Date|Resumption_of_Care_Date_NA|Resumption_of_Care_Date|Patient_State|Patient_ZIP_Code|Patient_Birth_Date|Gender|American_Indian_or_Alaska_Native|Asian|Black_or_African_American|Hispanic_or_Latino|Native_Hawiian_or_Pacific_Islander|Unknown_Race_Ethnicity|White|Medicare_Fee_For_Service|Medicare_HMO_Managed_Care|Date_of_Last_Home_Visit|Discharge_Transfer_Death_Date|Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode|Discharged_Past_14_Days_From_IPPS|Discharged_Past_14_Days_From_IRF|Discharged_Past_14_Days_From_LTC|Discharged_Past_14_Days_From_LTCH|Discharged_Past_14_Days_From_Other|Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit|Discharged_Past_14_Days_From_SNF_TCU|Discharged_Past_14_Days_NA|Most_Recent_Inpat_Discharge_Date_UK|Most_Recent_Inpatient_Discharge_Date|Therapies_In_Home_Enteral_Nutrition|Therapies_In_Home_IV_Infusion|Therapies_In_Home_None_Above|Therapies_In_Home_Parenteral_Nutrition|Patient_Overall_Status|High_Risk_Factor_Alcohol_Dependency|High_Risk_Factor_Drug_Dependency|High_Risk_Factor_None_Of_The_Above|High_Risk_Factor_Obesity|High_Risk_Factor_Smoking|High_Risk_Factor_UK|Patient_Living_Situation|Vision|Ability_To_Hear|Understanding_Of_Verbal_Content|Speech_And_Oral_Expression|Formal_Pain_Assessment|Frequency_Of_Pain_Interfering_With_Activity|Pressure_Ulcer_Assessment|Risk_Of_Developing_Pressure_Ulcers|Unhealed_Pressure_Ulcer_at_Least_Stage_II|Oldest_Stage_II_Onset_Date|Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge|Status_Of_Most_Problematic_Pressure_Ulcer|Current_Number_Of_Stage_I_Pressure_Ulcers|Stage_Of_Most_Problematic_Pressure_Ulcer|Stasis_Ulcer_Present|Current_Number_Of_(Observable)_Stasis_Ulcers|Status_Of_Most_Problematic_Stasis_Ulcer|Does_This_Patient_Have_A_Surgical_Wound|Status_Of_Most_Problematic_Surgical_Wound|Skin_Lesion_Or_Open_Wound|When_Is_Patient_Dyspneic|Resprtry_Treat_At_Home_Airway_Press|Resprtry_Treat_At_Home_None|Resprtry_Treat_At_Home_Oxygen|Resprtry_Treat_At_Home_Ventilator|Patient_Treated_For_UTI_Last_14_Days|Urinary_Incontinence_Or_Catheter_Presence|When_Does_Urinary_Incontinence_Occur|Bowel_Incontinence_Frequency|Ostomy_For_Bowel_Elimination|Cognitive_Functioning|When_Confused|When_Anxious|Depression_Screening|Feeling_Down_Depressed_Or_Hopeless|Little_Interest_Or_Pleasure_In_Doing_Things|Cog_Behavr_Psych_Symp_Delusional|Cog_Behavr_Psych_Symp_Impaired_Decision|Cog_Behavr_Psych_Symp_Memory_Deficit|Cog_Behavr_Psych_Symp_None_Of_The_Above|Cog_Behavr_Psych_Symp_Physical_Aggression|Cog_Behavr_Psych_Symp_Socially_Inapp|Cog_Behavr_Psych_Symp_Verbal_Disruption|Frequency_Of_Disruptive_Behavior_Symptoms|Receives_Psych_Nursing_Services|Current_Grooming|Current_Dress_Upper|Current_Dress_Lower|Current_Bathing|Toilet_Transferring|Current_Toileting_Hygiene|Transferring|Ambulation_Locomotion|Current_Feeding|Current_Preparing_Light_Meals|Current_Phone_Use|Prior_Functioning_ADL_IADL_Ambulation|Prior_Functioning_ADL_IADL_Household_Tasks|Prior_Functioning_ADL_IADL_Self_Care|Prior_Functioning_ADL_IADL_Transfer|Multi_Factor_Fall_Risk_Assessment|Patient_Caregiver_High_Risk_Drug_Educ|Current_Management_Of_Oral_Medications|Current_Management_Of_Injectable_Meds|Prior_Medication_Management_Injectable_Meds|Prior_Medication_Management_Oral_Meds|Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver|Therapy_Need_NA|Therapy_Need_Number_Of_Visits|Plan_Of_Care_Synopsis_At_Risk_For_Falls|Plan_Of_Care_Synopsis_Depression|Plan_Of_Care_Synopsis_Diabetic_Foot_Care|Plan_Of_Care_Synopsis_Pain_Intervention|Plan_Of_Care_Synopsis_Patient_Specific|Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment|Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention|Emergent_Care_Reason_Acute_Mental_Behavioral|Emergent_Care_Reason_Cardiac_Dysrhythmia|Emergent_Care_Reason_Dehydration_Malnutrition|Emergent_Care_Reason_DVT_Pulmonary_Embolus|Emergent_Care_Reason_GI_Issues|Emergent_Care_Reason_Heart_Failure|Emergent_Care_Hypo_Hyperglycemia|Emergent_Care_Improper_Medication_Administration|Emergent_Care_Reason_Injury_Caused_By_Fall|Emergent_Care_Reason_IV_Catheter_Infection|Emergent_Care_Reason_Myocardial_Infarction|Emergent_Care_Reason_Other_Heart_Disease|Emergent_Care_Reason_Other_Respiratory_Problem|Emergent_Care_Reason_Other_Than_Above|Emergent_Care_Reason_Unknown|Emergent_Care_Reason_Respiratory_Infection|Emergent_Care_Reason_Stroke_CVA_Or_TIA|Emergent_Care_Reason_Uncontrolled_Pain|Emergent_Care_Reason_Urinary_Tract_Infection|Emergent_Care_Reason_Wound_Infection_Or_Deter|Inpatient_Facility_Admitted|Discharge_Disposition|Hospital_Reason_Acute_Mental_Behavioral|Hospital_Reason_Cardiac_Dysrhythmia|Hospital_Reason_Dehydration_Malnutrition|Hospital_Reason_DVT_Pulmonary_Embolus|Hospital_Reason_GI_Issues|Hospital_Reason_Heart_Failure|Hospital_Reason_Hypo_Hyperglycemic|Hospital_Reason_Improper_Medication_Administration|Hospital_Reason_Injury_Caused_By_Fall|Hospital_Reason_IV_Catheter_Infection_Complication|Hospital_Reason_Myocardial_Infarction|Hospital_Reason_Other_Heart_Disease|Hospital_Reason_Other_Respiratory_Problem|Hospital_Reason_Other_Than_Above|Hospital_Reason_Reason_Unknown|Hospital_Reason_Respiratory_Infection|Hospital_Reason_Scheduled_Treatment_Or_Procedure|Hospital_Reason_Stroke_CVA_Or_TIA|Hospital_Reason_Uncontrolled_Pain|Hospital_Reason_Urinary_Tract_Infect|Hospital_Reason_Wound_Infection_Deterioration|Inpatient_Diagnosis_1_ICD_10_C_M|Inpatient_Diagnosis_2_ICD_10_C_M|Inpatient_Diagnosis_3_ICD_10_C_M|Inpatient_Diagnosis_4_ICD_10_C_M|Inpatient_Diagnosis_5_ICD_10_C_M|Inpatient_Diagnosis_6_ICD_10_C_M|Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable|Regimen_Change_Diagnosis_1_ICD_10_C_M|Regimen_Change_Diagnosis_2_ICD_10_C_M|Regimen_Change_Diagnosis_3_ICD_10_C_M|Regimen_Change_Diagnosis_4_ICD_10_C_M|Regimen_Change_Diagnosis_5_ICD_10_C_M|Regimen_Change_Diagnosis_6_ICD_10_C_M|Regimen_Change_Not_Applicable_ICD_10_C_M_Code|Primary_Diagnosis_ICD_10_C_M_Code|Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code|Other_Diagnosis_Code_1_ICD_10_C_M|Other_Diagnosis_Code_1_Severity_ICD_10_C_M|Other_Diagnosis_Code_2_ICD_10_C_M|Other_Diagnosis_Code_2_Severity_ICD_10_C_M|Other_Diagnosis_Code_3_ICD_10_C_M|Other_Diagnosis_Code_3_Severity_ICD_10_C_M|Other_Diagnosis_Code_4_ICD_10_C_M|Other_Diagnosis_Code_4_Severity_ICD_10_C_M|Other_Diagnosis_Code_5_ICD_10_C_M|Other_Diagnosis_Code_5_Severity_ICD_10_C_M|Primary_Optional_Diagnosis_ICD_10_C_M_Code|Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M|Optional_Diagnosis_Code_1_ICD_10_C_M|Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M|Optional_Diagnosis_Code_2_ICD_10_C_M|Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M|Optional_Diagnosis_Code_3_ICD_10_C_M|Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M|Optional_Diagnosis_Code_4_ICD_10_C_M|Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M|Optional_Diagnosis_Code_5_ICD_10_C_M|Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M|Risk_for_Hospitalization_Fall_History|Risk_For_Hospitalization_Weight_Loss|Risk_For_Hospitalization_Multiple_Hospitalizations|Risk_For_Hospitalization_Multiple_ER_Visits|Risk_For_Hospitalization_Mental_Emotional_Behavioral|Risk_For_Hospitalization_Difficulty_with_Medical_Instructions|Risk_For_Hospitalization_Taking_Five_or_More_Meds|Risk_For_Hospitalization_Exhaustion|Risk_For_Hospitalization_Other|Risk_For_Hospitalization_None_of_the_Above|Care_Assistance_ADL_Assistance|Care_Assistance_IADL_Assistance|Care_Assistance_Medication_Administration|Care_Assistance_Medical_Procedures_Treatments|Care_Assistance_Management_of_Equipment|Care_Assistance_Supervision_And_Safety|Care_Assistance_Advocacy_Or_Facilitation|Heart_failure_follow_up_phys_ordered_treatmnt|Mobility_Discharge_Goal_Lying_to_Sitting|Mobility_SOC_ROC_Performance_Lying_to_Sitting|HHA_Agency_ID|Active_Diagnoses_Diabetes_Mellitus|Active_Diagnoses_PVD_or_PAD|Height_in_inches|Weight_in_pounds|Number_of_Stage_2_Pressure_Ulcers|Number_of_Stage_2_pressure_ulcers_at_SOC_ROC|Number_of_Stage_3_Pressure_Ulcers|Number_of_Stage_3_pressure_ulcers_at_SOC_ROC|Number_of_Stage_4_Pressure_Ulcers|Number_of_Stage_4_pressure_ulcers_at_SOC_ROC|Unstageable_coverage_by_slough_or_eschar|Unstageable_coverage_by_slough_or_eschar_SOC_ROC|Unstageable_suspect_deep_tissue_injury|Unstageable_suspect_deep_tissue_injury_SOC_ROC|Num_unstage_pressure_ulcer_non_remov_dress|Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC|New_worsening_Stage_2|New_worsening_Stage_3|New_worsening_Stage_4|New_worsening_unstageable_non_removable_drs_dv|New_worsening_unstageable_coverage_slough_eschar|New_worsening_unstageable_deep_tissue_injury|Symptoms_in_heart_failure_patients|Heart_failure_follow_up_change_in_care_plan|Heart_failure_follow_up_pt_educ_other_clinical|Heart_failure_follow_up_ER_treatment_advised|Heart_failure_follow_up_no_action|Heart_failure_follow_up_physician_contacted|Drug_regimen_review|Medication_follow_up|Medication_intervention|Patient_caregiver_drug_education_intervention|Emergent_care_use_since_most_recent_SOC_ROC|Intervention_synopsis_diabetic_foot_care|Intervention_synopsis_depression_intervention|Intervention_synopsis_falls_prevention|Intervention_synopsis_monitor_and_mitigate_pain|Intervention_synopsis_prevent_pressure_ulcers|Intervention_synopsis_PU_moist_wound_treatment|AssessmentYear|NumVisits|PrevVisitDate|DaysBetweenVisits|Last_Assessment_Date|Days_Cared_For|Age|ByDiscipline|A00-B99|C00-D49|D50-D89|E00-E89|F01-F99|G00-G99|H00-H59|H60-H95|I00-I99|J00-J99|K00-K95|L00-L99|M00-M99|N00-N99|O00-O9A|P00-P96|Q00-Q99|R00-R99|S00-T88|U00-U85|V00-Y99|Z00-Z99|

In [6]:
df.columns

['Beneficiary_ID',
 'Assessment_ID',
 'Assessment_Effective_Date',
 'Calculated_HIPPS_Code',
 'Facility_Internal_ID',
 'HHA_Assessment_Internal_ID',
 'State_ID',
 'Submission_Date',
 'Submitted_HIPPS_Code',
 'Agency_Medicare_Number',
 'Branch_State',
 'Branch_Identifier_Number',
 'Start_of_Care_Date',
 'Resumption_of_Care_Date_NA',
 'Resumption_of_Care_Date',
 'Patient_State',
 'Patient_ZIP_Code',
 'Patient_Birth_Date',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'Medicare_Fee_For_Service',
 'Medicare_HMO_Managed_Care',
 'Date_of_Last_Home_Visit',
 'Discharge_Transfer_Death_Date',
 'Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode',
 'Discharged_Past_14_Days_From_IPPS',
 'Discharged_Past_14_Days_From_IRF',
 'Discharged_Past_14_Days_From_LTC',
 'Discharged_Past_14_Days_From_LTCH',
 'Discharged_Past_14_Days_From_Other',
 'Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit',
 'Discharged_Past_14_Days_From_SNF_TCU',
 'Discharged_Past_14_Days_NA',
 'Most_Recent_Inpat_Discharge_Date_UK',
 'Most_Recent_Inpatient_Discharge_Date',
 'Therapies_In_Home_Enteral_Nutrition',
 'Therapies_In_Home_IV_Infusion',
 'Therapies_In_Home_None_Above',
 'Therapies_In_Home_Parenteral_Nutrition',
 'Patient_Overall_Status',
 'High_Risk_Factor_Alcohol_Dependency',
 'High_Risk_Factor_Drug_Dependency',
 'High_Risk_Factor_None_Of_The_Above',
 'High_Risk_Factor_Obesity',
 'High_Risk_Factor_Smoking',
 'High_Risk_Factor_UK',
 'Patient_Living_Situation',
 'Vision',
 'Ability_To_Hear',
 'Understanding_Of_Verbal_Content',
 'Speech_And_Oral_Expression',
 'Formal_Pain_Assessment',
 'Frequency_Of_Pain_Interfering_With_Activity',
 'Pressure_Ulcer_Assessment',
 'Risk_Of_Developing_Pressure_Ulcers',
 'Unhealed_Pressure_Ulcer_at_Least_Stage_II',
 'Oldest_Stage_II_Onset_Date',
 'Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge',
 'Status_Of_Most_Problematic_Pressure_Ulcer',
 'Current_Number_Of_Stage_I_Pressure_Ulcers',
 'Stage_Of_Most_Problematic_Pressure_Ulcer',
 'Stasis_Ulcer_Present',
 'Current_Number_Of_(Observable)_Stasis_Ulcers',
 'Status_Of_Most_Problematic_Stasis_Ulcer',
 'Does_This_Patient_Have_A_Surgical_Wound',
 'Status_Of_Most_Problematic_Surgical_Wound',
 'Skin_Lesion_Or_Open_Wound',
 'When_Is_Patient_Dyspneic',
 'Resprtry_Treat_At_Home_Airway_Press',
 'Resprtry_Treat_At_Home_None',
 'Resprtry_Treat_At_Home_Oxygen',
 'Resprtry_Treat_At_Home_Ventilator',
 'Patient_Treated_For_UTI_Last_14_Days',
 'Urinary_Incontinence_Or_Catheter_Presence',
 'When_Does_Urinary_Incontinence_Occur',
 'Bowel_Incontinence_Frequency',
 'Ostomy_For_Bowel_Elimination',
 'Cognitive_Functioning',
 'When_Confused',
 'When_Anxious',
 'Depression_Screening',
 'Feeling_Down_Depressed_Or_Hopeless',
 'Little_Interest_Or_Pleasure_In_Doing_Things',
 'Cog_Behavr_Psych_Symp_Delusional',
 'Cog_Behavr_Psych_Symp_Impaired_Decision',
 'Cog_Behavr_Psych_Symp_Memory_Deficit',
 'Cog_Behavr_Psych_Symp_None_Of_The_Above',
 'Cog_Behavr_Psych_Symp_Physical_Aggression',
 'Cog_Behavr_Psych_Symp_Socially_Inapp',
 'Cog_Behavr_Psych_Symp_Verbal_Disruption',
 'Frequency_Of_Disruptive_Behavior_Symptoms',
 'Receives_Psych_Nursing_Services',
 'Current_Grooming',
 'Current_Dress_Upper',
 'Current_Dress_Lower',
 'Current_Bathing',
 'Toilet_Transferring',
 'Current_Toileting_Hygiene',
 'Transferring',
 'Ambulation_Locomotion',
 'Current_Feeding',
 'Current_Preparing_Light_Meals',
 'Current_Phone_Use',
 'Prior_Functioning_ADL_IADL_Ambulation',
 'Prior_Functioning_ADL_IADL_Household_Tasks',
 'Prior_Functioning_ADL_IADL_Self_Care',
 'Prior_Functioning_ADL_IADL_Transfer',
 'Multi_Factor_Fall_Risk_Assessment',
 'Patient_Caregiver_High_Risk_Drug_Educ',
 'Current_Management_Of_Oral_Medications',
 'Current_Management_Of_Injectable_Meds',
 'Prior_Medication_Management_Injectable_Meds',
 'Prior_Medication_Management_Oral_Meds',
 'Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver',
 'Therapy_Need_NA',
 'Therapy_Need_Number_Of_Visits',
 'Plan_Of_Care_Synopsis_At_Risk_For_Falls',
 'Plan_Of_Care_Synopsis_Depression',
 'Plan_Of_Care_Synopsis_Diabetic_Foot_Care',
 'Plan_Of_Care_Synopsis_Pain_Intervention',
 'Plan_Of_Care_Synopsis_Patient_Specific',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention',
 'Emergent_Care_Reason_Acute_Mental_Behavioral',
 'Emergent_Care_Reason_Cardiac_Dysrhythmia',
 'Emergent_Care_Reason_Dehydration_Malnutrition',
 'Emergent_Care_Reason_DVT_Pulmonary_Embolus',
 'Emergent_Care_Reason_GI_Issues',
 'Emergent_Care_Reason_Heart_Failure',
 'Emergent_Care_Hypo_Hyperglycemia',
 'Emergent_Care_Improper_Medication_Administration',
 'Emergent_Care_Reason_Injury_Caused_By_Fall',
 'Emergent_Care_Reason_IV_Catheter_Infection',
 'Emergent_Care_Reason_Myocardial_Infarction',
 'Emergent_Care_Reason_Other_Heart_Disease',
 'Emergent_Care_Reason_Other_Respiratory_Problem',
 'Emergent_Care_Reason_Other_Than_Above',
 'Emergent_Care_Reason_Unknown',
 'Emergent_Care_Reason_Respiratory_Infection',
 'Emergent_Care_Reason_Stroke_CVA_Or_TIA',
 'Emergent_Care_Reason_Uncontrolled_Pain',
 'Emergent_Care_Reason_Urinary_Tract_Infection',
 'Emergent_Care_Reason_Wound_Infection_Or_Deter',
 'Inpatient_Facility_Admitted',
 'Discharge_Disposition',
 'Hospital_Reason_Acute_Mental_Behavioral',
 'Hospital_Reason_Cardiac_Dysrhythmia',
 'Hospital_Reason_Dehydration_Malnutrition',
 'Hospital_Reason_DVT_Pulmonary_Embolus',
 'Hospital_Reason_GI_Issues',
 'Hospital_Reason_Heart_Failure',
 'Hospital_Reason_Hypo_Hyperglycemic',
 'Hospital_Reason_Improper_Medication_Administration',
 'Hospital_Reason_Injury_Caused_By_Fall',
 'Hospital_Reason_IV_Catheter_Infection_Complication',
 'Hospital_Reason_Myocardial_Infarction',
 'Hospital_Reason_Other_Heart_Disease',
 'Hospital_Reason_Other_Respiratory_Problem',
 'Hospital_Reason_Other_Than_Above',
 'Hospital_Reason_Reason_Unknown',
 'Hospital_Reason_Respiratory_Infection',
 'Hospital_Reason_Scheduled_Treatment_Or_Procedure',
 'Hospital_Reason_Stroke_CVA_Or_TIA',
 'Hospital_Reason_Uncontrolled_Pain',
 'Hospital_Reason_Urinary_Tract_Infect',
 'Hospital_Reason_Wound_Infection_Deterioration',
 'Inpatient_Diagnosis_1_ICD_10_C_M',
 'Inpatient_Diagnosis_2_ICD_10_C_M',
 'Inpatient_Diagnosis_3_ICD_10_C_M',
 'Inpatient_Diagnosis_4_ICD_10_C_M',
 'Inpatient_Diagnosis_5_ICD_10_C_M',
 'Inpatient_Diagnosis_6_ICD_10_C_M',
 'Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable',
 'Regimen_Change_Diagnosis_1_ICD_10_C_M',
 'Regimen_Change_Diagnosis_2_ICD_10_C_M',
 'Regimen_Change_Diagnosis_3_ICD_10_C_M',
 'Regimen_Change_Diagnosis_4_ICD_10_C_M',
 'Regimen_Change_Diagnosis_5_ICD_10_C_M',
 'Regimen_Change_Diagnosis_6_ICD_10_C_M',
 'Regimen_Change_Not_Applicable_ICD_10_C_M_Code',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_1_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_2_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_3_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_4_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Other_Diagnosis_Code_5_Severity_ICD_10_C_M',
 'Primary_Optional_Diagnosis_ICD_10_C_M_Code',
 'Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M',
 'Optional_Diagnosis_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Code_5_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M',
 'Risk_for_Hospitalization_Fall_History',
 'Risk_For_Hospitalization_Weight_Loss',
 'Risk_For_Hospitalization_Multiple_Hospitalizations',
 'Risk_For_Hospitalization_Multiple_ER_Visits',
 'Risk_For_Hospitalization_Mental_Emotional_Behavioral',
 'Risk_For_Hospitalization_Difficulty_with_Medical_Instructions',
 'Risk_For_Hospitalization_Taking_Five_or_More_Meds',
 'Risk_For_Hospitalization_Exhaustion',
 'Risk_For_Hospitalization_Other',
 'Risk_For_Hospitalization_None_of_the_Above',
 'Care_Assistance_ADL_Assistance',
 'Care_Assistance_IADL_Assistance',
 'Care_Assistance_Medication_Administration',
 'Care_Assistance_Medical_Procedures_Treatments',
 'Care_Assistance_Management_of_Equipment',
 'Care_Assistance_Supervision_And_Safety',
 'Care_Assistance_Advocacy_Or_Facilitation',
 'Heart_failure_follow_up_phys_ordered_treatmnt',
 'Mobility_Discharge_Goal_Lying_to_Sitting',
 'Mobility_SOC_ROC_Performance_Lying_to_Sitting',
 'HHA_Agency_ID',
 'Active_Diagnoses_Diabetes_Mellitus',
 'Active_Diagnoses_PVD_or_PAD',
 'Height_in_inches',
 'Weight_in_pounds',
 'Number_of_Stage_2_Pressure_Ulcers',
 'Number_of_Stage_2_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_3_Pressure_Ulcers',
 'Number_of_Stage_3_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_4_Pressure_Ulcers',
 'Number_of_Stage_4_pressure_ulcers_at_SOC_ROC',
 'Unstageable_coverage_by_slough_or_eschar',
 'Unstageable_coverage_by_slough_or_eschar_SOC_ROC',
 'Unstageable_suspect_deep_tissue_injury',
 'Unstageable_suspect_deep_tissue_injury_SOC_ROC',
 'Num_unstage_pressure_ulcer_non_remov_dress',
 'Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC',
 'New_worsening_Stage_2',
 'New_worsening_Stage_3',
 'New_worsening_Stage_4',
 'New_worsening_unstageable_non_removable_drs_dv',
 'New_worsening_unstageable_coverage_slough_eschar',
 'New_worsening_unstageable_deep_tissue_injury',
 'Symptoms_in_heart_failure_patients',
 'Heart_failure_follow_up_change_in_care_plan',
 'Heart_failure_follow_up_pt_educ_other_clinical',
 'Heart_failure_follow_up_ER_treatment_advised',
 'Heart_failure_follow_up_no_action',
 'Heart_failure_follow_up_physician_contacted',
 'Drug_regimen_review',
 'Medication_follow_up',
 'Medication_intervention',
 'Patient_caregiver_drug_education_intervention',
 'Emergent_care_use_since_most_recent_SOC_ROC',
 'Intervention_synopsis_diabetic_foot_care',
 'Intervention_synopsis_depression_intervention',
 'Intervention_synopsis_falls_prevention',
 'Intervention_synopsis_monitor_and_mitigate_pain',
 'Intervention_synopsis_prevent_pressure_ulcers',
 'Intervention_synopsis_PU_moist_wound_treatment',
 'AssessmentYear',
 'NumVisits',
 'PrevVisitDate',
 'DaysBetweenVisits',
 'Last_Assessment_Date',
 'Days_Cared_For',
 'Age',
 'ByDiscipline',
 'A00-B99',
 'C00-D49',
 'D50-D89',
 'E00-E89',
 'F01-F99',
 'G00-G99',
 'H00-H59',
 'H60-H95',
 'I00-I99',
 'J00-J99',
 'K00-K95',
 'L00-L99',
 'M00-M99',
 'N00-N99',
 'O00-O9A',
 'P00-P96',
 'Q00-Q99',
 'R00-R99',
 'S00-T88',
 'U00-U85',
 'V00-Y99',
 'Z00-Z99']

In [7]:
dates = [
    col for col in df.columns 
    if col.startswith("Date") 
    or col.startswith("date") 
    or col.endswith("Date") 
    or col.endswith("date")
]

for d in dates:
    df = df.withColumn(d, F.to_date(F.col(d), "ddMMMyyyy"))

In [8]:
df.printSchema()

root
 |-- Beneficiary_ID: string (nullable = true)
 |-- Assessment_ID: string (nullable = true)
 |-- Assessment_Effective_Date: date (nullable = true)
 |-- Calculated_HIPPS_Code: string (nullable = true)
 |-- Facility_Internal_ID: integer (nullable = true)
 |-- HHA_Assessment_Internal_ID: string (nullable = true)
 |-- State_ID: string (nullable = true)
 |-- Submission_Date: date (nullable = true)
 |-- Submitted_HIPPS_Code: string (nullable = true)
 |-- Agency_Medicare_Number: string (nullable = true)
 |-- Branch_State: string (nullable = true)
 |-- Branch_Identifier_Number: string (nullable = true)
 |-- Start_of_Care_Date: date (nullable = true)
 |-- Resumption_of_Care_Date_NA: integer (nullable = true)
 |-- Resumption_of_Care_Date: date (nullable = true)
 |-- Patient_State: string (nullable = true)
 |-- Patient_ZIP_Code: integer (nullable = true)
 |-- Patient_Birth_Date: date (nullable = true)
 |-- Gender: string (nullable = true)
 |-- American_Indian_or_Alaska_Native: integer (nullable = true)
 |-- Asian: integer (nullable = true)
 |-- Black_or_African_American: integer (nullable = true)
 |-- Hispanic_or_Latino: integer (nullable = true)
 |-- Native_Hawiian_or_Pacific_Islander: integer (nullable = true)
 |-- Unknown_Race_Ethnicity: string (nullable = true)
 |-- White: integer (nullable = true)
 |-- Medicare_Fee_For_Service: integer (nullable = true)
 |-- Medicare_HMO_Managed_Care: integer (nullable = true)
 |-- Date_of_Last_Home_Visit: date (nullable = true)
 |-- Discharge_Transfer_Death_Date: date (nullable = true)
 |-- Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode: string (nullable = true)
 |-- Discharged_Past_14_Days_From_IPPS: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_IRF: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_LTC: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_LTCH: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_Other: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit: integer (nullable = true)
 |-- Discharged_Past_14_Days_From_SNF_TCU: integer (nullable = true)
 |-- Discharged_Past_14_Days_NA: integer (nullable = true)
 |-- Most_Recent_Inpat_Discharge_Date_UK: integer (nullable = true)
 |-- Most_Recent_Inpatient_Discharge_Date: date (nullable = true)
 |-- Therapies_In_Home_Enteral_Nutrition: integer (nullable = true)
 |-- Therapies_In_Home_IV_Infusion: integer (nullable = true)
 |-- Therapies_In_Home_None_Above: integer (nullable = true)
 |-- Therapies_In_Home_Parenteral_Nutrition: integer (nullable = true)
 |-- Patient_Overall_Status: string (nullable = true)
 |-- High_Risk_Factor_Alcohol_Dependency: integer (nullable = true)
 |-- High_Risk_Factor_Drug_Dependency: integer (nullable = true)
 |-- High_Risk_Factor_None_Of_The_Above: integer (nullable = true)
 |-- High_Risk_Factor_Obesity: integer (nullable = true)
 |-- High_Risk_Factor_Smoking: integer (nullable = true)
 |-- High_Risk_Factor_UK: integer (nullable = true)
 |-- Patient_Living_Situation: integer (nullable = true)
 |-- Vision: integer (nullable = true)
 |-- Ability_To_Hear: string (nullable = true)
 |-- Understanding_Of_Verbal_Content: string (nullable = true)
 |-- Speech_And_Oral_Expression: integer (nullable = true)
 |-- Formal_Pain_Assessment: integer (nullable = true)
 |-- Frequency_Of_Pain_Interfering_With_Activity: integer (nullable = true)
 |-- Pressure_Ulcer_Assessment: integer (nullable = true)
 |-- Risk_Of_Developing_Pressure_Ulcers: integer (nullable = true)
 |-- Unhealed_Pressure_Ulcer_at_Least_Stage_II: integer (nullable = true)
 |-- Oldest_Stage_II_Onset_Date: date (nullable = true)
 |-- Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge: string (nullable = true)
 |-- Status_Of_Most_Problematic_Pressure_Ulcer: string (nullable = true)
 |-- Current_Number_Of_Stage_I_Pressure_Ulcers: integer (nullable = true)
 |-- Stage_Of_Most_Problematic_Pressure_Ulcer: string (nullable = true)
 |-- Stasis_Ulcer_Present: integer (nullable = true)
 |-- Current_Number_Of_(Observable)_Stasis_Ulcers: integer (nullable = true)
 |-- Status_Of_Most_Problematic_Stasis_Ulcer: integer (nullable = true)
 |-- Does_This_Patient_Have_A_Surgical_Wound: integer (nullable = true)
 |-- Status_Of_Most_Problematic_Surgical_Wound: integer (nullable = true)
 |-- Skin_Lesion_Or_Open_Wound: integer (nullable = true)
 |-- When_Is_Patient_Dyspneic: integer (nullable = true)
 |-- Resprtry_Treat_At_Home_Airway_Press: integer (nullable = true)
 |-- Resprtry_Treat_At_Home_None: integer (nullable = true)
 |-- Resprtry_Treat_At_Home_Oxygen: integer (nullable = true)
 |-- Resprtry_Treat_At_Home_Ventilator: integer (nullable = true)
 |-- Patient_Treated_For_UTI_Last_14_Days: string (nullable = true)
 |-- Urinary_Incontinence_Or_Catheter_Presence: integer (nullable = true)
 |-- When_Does_Urinary_Incontinence_Occur: integer (nullable = true)
 |-- Bowel_Incontinence_Frequency: string (nullable = true)
 |-- Ostomy_For_Bowel_Elimination: integer (nullable = true)
 |-- Cognitive_Functioning: integer (nullable = true)
 |-- When_Confused: string (nullable = true)
 |-- When_Anxious: string (nullable = true)
 |-- Depression_Screening: integer (nullable = true)
 |-- Feeling_Down_Depressed_Or_Hopeless: string (nullable = true)
 |-- Little_Interest_Or_Pleasure_In_Doing_Things: string (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Delusional: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Impaired_Decision: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Memory_Deficit: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_None_Of_The_Above: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Physical_Aggression: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Socially_Inapp: integer (nullable = true)
 |-- Cog_Behavr_Psych_Symp_Verbal_Disruption: integer (nullable = true)
 |-- Frequency_Of_Disruptive_Behavior_Symptoms: integer (nullable = true)
 |-- Receives_Psych_Nursing_Services: integer (nullable = true)
 |-- Current_Grooming: integer (nullable = true)
 |-- Current_Dress_Upper: integer (nullable = true)
 |-- Current_Dress_Lower: integer (nullable = true)
 |-- Current_Bathing: integer (nullable = true)
 |-- Toilet_Transferring: integer (nullable = true)
 |-- Current_Toileting_Hygiene: integer (nullable = true)
 |-- Transferring: integer (nullable = true)
 |-- Ambulation_Locomotion: integer (nullable = true)
 |-- Current_Feeding: integer (nullable = true)
 |-- Current_Preparing_Light_Meals: integer (nullable = true)
 |-- Current_Phone_Use: string (nullable = true)
 |-- Prior_Functioning_ADL_IADL_Ambulation: integer (nullable = true)
 |-- Prior_Functioning_ADL_IADL_Household_Tasks: integer (nullable = true)
 |-- Prior_Functioning_ADL_IADL_Self_Care: integer (nullable = true)
 |-- Prior_Functioning_ADL_IADL_Transfer: integer (nullable = true)
 |-- Multi_Factor_Fall_Risk_Assessment: integer (nullable = true)
 |-- Patient_Caregiver_High_Risk_Drug_Educ: string (nullable = true)
 |-- Current_Management_Of_Oral_Medications: string (nullable = true)
 |-- Current_Management_Of_Injectable_Meds: string (nullable = true)
 |-- Prior_Medication_Management_Injectable_Meds: string (nullable = true)
 |-- Prior_Medication_Management_Oral_Meds: string (nullable = true)
 |-- Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver: string (nullable = true)
 |-- Therapy_Need_NA: integer (nullable = true)
 |-- Therapy_Need_Number_Of_Visits: integer (nullable = true)
 |-- Plan_Of_Care_Synopsis_At_Risk_For_Falls: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Depression: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Diabetic_Foot_Care: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Pain_Intervention: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Patient_Specific: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment: string (nullable = true)
 |-- Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention: string (nullable = true)
 |-- Emergent_Care_Reason_Acute_Mental_Behavioral: integer (nullable = true)
 |-- Emergent_Care_Reason_Cardiac_Dysrhythmia: integer (nullable = true)
 |-- Emergent_Care_Reason_Dehydration_Malnutrition: integer (nullable = true)
 |-- Emergent_Care_Reason_DVT_Pulmonary_Embolus: integer (nullable = true)
 |-- Emergent_Care_Reason_GI_Issues: integer (nullable = true)
 |-- Emergent_Care_Reason_Heart_Failure: integer (nullable = true)
 |-- Emergent_Care_Hypo_Hyperglycemia: integer (nullable = true)
 |-- Emergent_Care_Improper_Medication_Administration: integer (nullable = true)
 |-- Emergent_Care_Reason_Injury_Caused_By_Fall: integer (nullable = true)
 |-- Emergent_Care_Reason_IV_Catheter_Infection: integer (nullable = true)
 |-- Emergent_Care_Reason_Myocardial_Infarction: integer (nullable = true)
 |-- Emergent_Care_Reason_Other_Heart_Disease: integer (nullable = true)
 |-- Emergent_Care_Reason_Other_Respiratory_Problem: integer (nullable = true)
 |-- Emergent_Care_Reason_Other_Than_Above: integer (nullable = true)
 |-- Emergent_Care_Reason_Unknown: integer (nullable = true)
 |-- Emergent_Care_Reason_Respiratory_Infection: integer (nullable = true)
 |-- Emergent_Care_Reason_Stroke_CVA_Or_TIA: integer (nullable = true)
 |-- Emergent_Care_Reason_Uncontrolled_Pain: integer (nullable = true)
 |-- Emergent_Care_Reason_Urinary_Tract_Infection: integer (nullable = true)
 |-- Emergent_Care_Reason_Wound_Infection_Or_Deter: integer (nullable = true)
 |-- Inpatient_Facility_Admitted: string (nullable = true)
 |-- Discharge_Disposition: string (nullable = true)
 |-- Hospital_Reason_Acute_Mental_Behavioral: integer (nullable = true)
 |-- Hospital_Reason_Cardiac_Dysrhythmia: integer (nullable = true)
 |-- Hospital_Reason_Dehydration_Malnutrition: integer (nullable = true)
 |-- Hospital_Reason_DVT_Pulmonary_Embolus: integer (nullable = true)
 |-- Hospital_Reason_GI_Issues: integer (nullable = true)
 |-- Hospital_Reason_Heart_Failure: integer (nullable = true)
 |-- Hospital_Reason_Hypo_Hyperglycemic: integer (nullable = true)
 |-- Hospital_Reason_Improper_Medication_Administration: integer (nullable = true)
 |-- Hospital_Reason_Injury_Caused_By_Fall: integer (nullable = true)
 |-- Hospital_Reason_IV_Catheter_Infection_Complication: integer (nullable = true)
 |-- Hospital_Reason_Myocardial_Infarction: integer (nullable = true)
 |-- Hospital_Reason_Other_Heart_Disease: integer (nullable = true)
 |-- Hospital_Reason_Other_Respiratory_Problem: integer (nullable = true)
 |-- Hospital_Reason_Other_Than_Above: integer (nullable = true)
 |-- Hospital_Reason_Reason_Unknown: integer (nullable = true)
 |-- Hospital_Reason_Respiratory_Infection: integer (nullable = true)
 |-- Hospital_Reason_Scheduled_Treatment_Or_Procedure: integer (nullable = true)
 |-- Hospital_Reason_Stroke_CVA_Or_TIA: integer (nullable = true)
 |-- Hospital_Reason_Uncontrolled_Pain: integer (nullable = true)
 |-- Hospital_Reason_Urinary_Tract_Infect: integer (nullable = true)
 |-- Hospital_Reason_Wound_Infection_Deterioration: integer (nullable = true)
 |-- Inpatient_Diagnosis_1_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_2_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_3_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_4_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_5_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_6_ICD_10_C_M: string (nullable = true)
 |-- Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable: integer (nullable = true)
 |-- Regimen_Change_Diagnosis_1_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Diagnosis_2_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Diagnosis_3_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Diagnosis_4_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Diagnosis_5_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Diagnosis_6_ICD_10_C_M: string (nullable = true)
 |-- Regimen_Change_Not_Applicable_ICD_10_C_M_Code: integer (nullable = true)
 |-- Primary_Diagnosis_ICD_10_C_M_Code: string (nullable = true)
 |-- Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code: integer (nullable = true)
 |-- Other_Diagnosis_Code_1_ICD_10_C_M: string (nullable = true)
 |-- Other_Diagnosis_Code_1_Severity_ICD_10_C_M: integer (nullable = true)
 |-- Other_Diagnosis_Code_2_ICD_10_C_M: string (nullable = true)
 |-- Other_Diagnosis_Code_2_Severity_ICD_10_C_M: integer (nullable = true)
 |-- Other_Diagnosis_Code_3_ICD_10_C_M: string (nullable = true)
 |-- Other_Diagnosis_Code_3_Severity_ICD_10_C_M: integer (nullable = true)
 |-- Other_Diagnosis_Code_4_ICD_10_C_M: string (nullable = true)
 |-- Other_Diagnosis_Code_4_Severity_ICD_10_C_M: integer (nullable = true)
 |-- Other_Diagnosis_Code_5_ICD_10_C_M: string (nullable = true)
 |-- Other_Diagnosis_Code_5_Severity_ICD_10_C_M: integer (nullable = true)
 |-- Primary_Optional_Diagnosis_ICD_10_C_M_Code: string (nullable = true)
 |-- Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Code_1_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Code_2_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Code_3_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Code_4_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Code_5_ICD_10_C_M: string (nullable = true)
 |-- Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M: string (nullable = true)
 |-- Risk_for_Hospitalization_Fall_History: integer (nullable = true)
 |-- Risk_For_Hospitalization_Weight_Loss: integer (nullable = true)
 |-- Risk_For_Hospitalization_Multiple_Hospitalizations: integer (nullable = true)
 |-- Risk_For_Hospitalization_Multiple_ER_Visits: integer (nullable = true)
 |-- Risk_For_Hospitalization_Mental_Emotional_Behavioral: integer (nullable = true)
 |-- Risk_For_Hospitalization_Difficulty_with_Medical_Instructions: integer (nullable = true)
 |-- Risk_For_Hospitalization_Taking_Five_or_More_Meds: integer (nullable = true)
 |-- Risk_For_Hospitalization_Exhaustion: integer (nullable = true)
 |-- Risk_For_Hospitalization_Other: integer (nullable = true)
 |-- Risk_For_Hospitalization_None_of_the_Above: integer (nullable = true)
 |-- Care_Assistance_ADL_Assistance: integer (nullable = true)
 |-- Care_Assistance_IADL_Assistance: integer (nullable = true)
 |-- Care_Assistance_Medication_Administration: integer (nullable = true)
 |-- Care_Assistance_Medical_Procedures_Treatments: integer (nullable = true)
 |-- Care_Assistance_Management_of_Equipment: integer (nullable = true)
 |-- Care_Assistance_Supervision_And_Safety: integer (nullable = true)
 |-- Care_Assistance_Advocacy_Or_Facilitation: integer (nullable = true)
 |-- Heart_failure_follow_up_phys_ordered_treatmnt: integer (nullable = true)
 |-- Mobility_Discharge_Goal_Lying_to_Sitting: string (nullable = true)
 |-- Mobility_SOC_ROC_Performance_Lying_to_Sitting: string (nullable = true)
 |-- HHA_Agency_ID: string (nullable = true)
 |-- Active_Diagnoses_Diabetes_Mellitus: string (nullable = true)
 |-- Active_Diagnoses_PVD_or_PAD: string (nullable = true)
 |-- Height_in_inches: string (nullable = true)
 |-- Weight_in_pounds: string (nullable = true)
 |-- Number_of_Stage_2_Pressure_Ulcers: integer (nullable = true)
 |-- Number_of_Stage_2_pressure_ulcers_at_SOC_ROC: integer (nullable = true)
 |-- Number_of_Stage_3_Pressure_Ulcers: integer (nullable = true)
 |-- Number_of_Stage_3_pressure_ulcers_at_SOC_ROC: integer (nullable = true)
 |-- Number_of_Stage_4_Pressure_Ulcers: integer (nullable = true)
 |-- Number_of_Stage_4_pressure_ulcers_at_SOC_ROC: integer (nullable = true)
 |-- Unstageable_coverage_by_slough_or_eschar: integer (nullable = true)
 |-- Unstageable_coverage_by_slough_or_eschar_SOC_ROC: integer (nullable = true)
 |-- Unstageable_suspect_deep_tissue_injury: integer (nullable = true)
 |-- Unstageable_suspect_deep_tissue_injury_SOC_ROC: integer (nullable = true)
 |-- Num_unstage_pressure_ulcer_non_remov_dress: integer (nullable = true)
 |-- Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC: integer (nullable = true)
 |-- New_worsening_Stage_2: string (nullable = true)
 |-- New_worsening_Stage_3: string (nullable = true)
 |-- New_worsening_Stage_4: string (nullable = true)
 |-- New_worsening_unstageable_non_removable_drs_dv: string (nullable = true)
 |-- New_worsening_unstageable_coverage_slough_eschar: string (nullable = true)
 |-- New_worsening_unstageable_deep_tissue_injury: string (nullable = true)
 |-- Symptoms_in_heart_failure_patients: string (nullable = true)
 |-- Heart_failure_follow_up_change_in_care_plan: integer (nullable = true)
 |-- Heart_failure_follow_up_pt_educ_other_clinical: integer (nullable = true)
 |-- Heart_failure_follow_up_ER_treatment_advised: integer (nullable = true)
 |-- Heart_failure_follow_up_no_action: integer (nullable = true)
 |-- Heart_failure_follow_up_physician_contacted: integer (nullable = true)
 |-- Drug_regimen_review: string (nullable = true)
 |-- Medication_follow_up: string (nullable = true)
 |-- Medication_intervention: string (nullable = true)
 |-- Patient_caregiver_drug_education_intervention: string (nullable = true)
 |-- Emergent_care_use_since_most_recent_SOC_ROC: string (nullable = true)
 |-- Intervention_synopsis_diabetic_foot_care: string (nullable = true)
 |-- Intervention_synopsis_depression_intervention: string (nullable = true)
 |-- Intervention_synopsis_falls_prevention: string (nullable = true)
 |-- Intervention_synopsis_monitor_and_mitigate_pain: string (nullable = true)
 |-- Intervention_synopsis_prevent_pressure_ulcers: string (nullable = true)
 |-- Intervention_synopsis_PU_moist_wound_treatment: string (nullable = true)
 |-- AssessmentYear: integer (nullable = true)
 |-- NumVisits: integer (nullable = true)
 |-- PrevVisitDate: date (nullable = true)
 |-- DaysBetweenVisits: integer (nullable = true)
 |-- Last_Assessment_Date: date (nullable = true)
 |-- Days_Cared_For: integer (nullable = true)
 |-- Age: integer (nullable = true)
 |-- ByDiscipline: string (nullable = true)
 |-- A00-B99: integer (nullable = true)
 |-- C00-D49: integer (nullable = true)
 |-- D50-D89: integer (nullable = true)
 |-- E00-E89: integer (nullable = true)
 |-- F01-F99: integer (nullable = true)
 |-- G00-G99: integer (nullable = true)
 |-- H00-H59: integer (nullable = true)
 |-- H60-H95: integer (nullable = true)
 |-- I00-I99: integer (nullable = true)
 |-- J00-J99: integer (nullable = true)
 |-- K00-K95: integer (nullable = true)
 |-- L00-L99: integer (nullable = true)
 |-- M00-M99: integer (nullable = true)
 |-- N00-N99: integer (nullable = true)
 |-- O00-O9A: integer (nullable = true)
 |-- P00-P96: integer (nullable = true)
 |-- Q00-Q99: integer (nullable = true)
 |-- R00-R99: integer (nullable = true)
 |-- S00-T88: integer (nullable = true)
 |-- U00-U85: integer (nullable = true)
 |-- V00-Y99: integer (nullable = true)
 |-- Z00-Z99: integer (nullable = true)

In [9]:
window_spec = Window.partitionBy("Beneficiary_ID", 'Assessment_Effective_Date').orderBy("Assessment_Effective_Date")
df = df.withColumn("NumVisits", F.count("Assessment_ID").over(window_spec))
df = df.withColumn("PrevVisitDate", F.lag("Assessment_Effective_Date").over(window_spec))
df = df.withColumn("DaysBetweenVisits", F.datediff("Assessment_Effective_Date", "PrevVisitDate"))

In [10]:
df = df.withColumn("Start_of_Care_Date", F.to_date("Start_of_Care_Date", "ddMMMyyyy"))
# Get the last resumption of care date per BENE_ID
last_admission = df.groupBy("Beneficiary_ID").agg(F.max("Assessment_Effective_Date").alias("Assessment_Effective_Date_last"))
# Merge with original dataframe to get the last admission date for each BENE_ID
df = df.join(last_admission, on="Beneficiary_ID", how="left")
# Calculate days cared for
df = df.withColumn("Days_Cared_For", F.datediff("Assessment_Effective_Date_last", "Start_of_Care_Date"))

In [11]:
df = df.withColumn(
    "READMISSION",
    when(datediff(col("Resumption_of_Care_Date"), col("Assessment_Effective_Date")) < 30, 1).otherwise(0)
)

In [12]:
df_counts = df.groupBy("READMISSION").count()
df_counts.show()

[Stage 3:======================================================>(110 + 2) / 112]

+-----------+--------+
|READMISSION|   count|
+-----------+--------+
|          0|14353049|
|          1| 1401281|
+-----------+--------+

In [13]:
df = df.withColumn("Patient_Birth_Date", F.to_date("Patient_Birth_Date", "ddMMMyyyy"))
df = df.withColumn("Age", datediff(col("Assessment_Effective_Date"), col("Patient_Birth_Date")) / 365)

In [14]:
df.columns

['Beneficiary_ID',
 'Assessment_ID',
 'Assessment_Effective_Date',
 'Calculated_HIPPS_Code',
 'Facility_Internal_ID',
 'HHA_Assessment_Internal_ID',
 'State_ID',
 'Submission_Date',
 'Submitted_HIPPS_Code',
 'Agency_Medicare_Number',
 'Branch_State',
 'Branch_Identifier_Number',
 'Start_of_Care_Date',
 'Resumption_of_Care_Date_NA',
 'Resumption_of_Care_Date',
 'Patient_State',
 'Patient_ZIP_Code',
 'Patient_Birth_Date',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'Medicare_Fee_For_Service',
 'Medicare_HMO_Managed_Care',
 'Date_of_Last_Home_Visit',
 'Discharge_Transfer_Death_Date',
 'Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode',
 'Discharged_Past_14_Days_From_IPPS',
 'Discharged_Past_14_Days_From_IRF',
 'Discharged_Past_14_Days_From_LTC',
 'Discharged_Past_14_Days_From_LTCH',
 'Discharged_Past_14_Days_From_Other',
 'Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit',
 'Discharged_Past_14_Days_From_SNF_TCU',
 'Discharged_Past_14_Days_NA',
 'Most_Recent_Inpat_Discharge_Date_UK',
 'Most_Recent_Inpatient_Discharge_Date',
 'Therapies_In_Home_Enteral_Nutrition',
 'Therapies_In_Home_IV_Infusion',
 'Therapies_In_Home_None_Above',
 'Therapies_In_Home_Parenteral_Nutrition',
 'Patient_Overall_Status',
 'High_Risk_Factor_Alcohol_Dependency',
 'High_Risk_Factor_Drug_Dependency',
 'High_Risk_Factor_None_Of_The_Above',
 'High_Risk_Factor_Obesity',
 'High_Risk_Factor_Smoking',
 'High_Risk_Factor_UK',
 'Patient_Living_Situation',
 'Vision',
 'Ability_To_Hear',
 'Understanding_Of_Verbal_Content',
 'Speech_And_Oral_Expression',
 'Formal_Pain_Assessment',
 'Frequency_Of_Pain_Interfering_With_Activity',
 'Pressure_Ulcer_Assessment',
 'Risk_Of_Developing_Pressure_Ulcers',
 'Unhealed_Pressure_Ulcer_at_Least_Stage_II',
 'Oldest_Stage_II_Onset_Date',
 'Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge',
 'Status_Of_Most_Problematic_Pressure_Ulcer',
 'Current_Number_Of_Stage_I_Pressure_Ulcers',
 'Stage_Of_Most_Problematic_Pressure_Ulcer',
 'Stasis_Ulcer_Present',
 'Current_Number_Of_(Observable)_Stasis_Ulcers',
 'Status_Of_Most_Problematic_Stasis_Ulcer',
 'Does_This_Patient_Have_A_Surgical_Wound',
 'Status_Of_Most_Problematic_Surgical_Wound',
 'Skin_Lesion_Or_Open_Wound',
 'When_Is_Patient_Dyspneic',
 'Resprtry_Treat_At_Home_Airway_Press',
 'Resprtry_Treat_At_Home_None',
 'Resprtry_Treat_At_Home_Oxygen',
 'Resprtry_Treat_At_Home_Ventilator',
 'Patient_Treated_For_UTI_Last_14_Days',
 'Urinary_Incontinence_Or_Catheter_Presence',
 'When_Does_Urinary_Incontinence_Occur',
 'Bowel_Incontinence_Frequency',
 'Ostomy_For_Bowel_Elimination',
 'Cognitive_Functioning',
 'When_Confused',
 'When_Anxious',
 'Depression_Screening',
 'Feeling_Down_Depressed_Or_Hopeless',
 'Little_Interest_Or_Pleasure_In_Doing_Things',
 'Cog_Behavr_Psych_Symp_Delusional',
 'Cog_Behavr_Psych_Symp_Impaired_Decision',
 'Cog_Behavr_Psych_Symp_Memory_Deficit',
 'Cog_Behavr_Psych_Symp_None_Of_The_Above',
 'Cog_Behavr_Psych_Symp_Physical_Aggression',
 'Cog_Behavr_Psych_Symp_Socially_Inapp',
 'Cog_Behavr_Psych_Symp_Verbal_Disruption',
 'Frequency_Of_Disruptive_Behavior_Symptoms',
 'Receives_Psych_Nursing_Services',
 'Current_Grooming',
 'Current_Dress_Upper',
 'Current_Dress_Lower',
 'Current_Bathing',
 'Toilet_Transferring',
 'Current_Toileting_Hygiene',
 'Transferring',
 'Ambulation_Locomotion',
 'Current_Feeding',
 'Current_Preparing_Light_Meals',
 'Current_Phone_Use',
 'Prior_Functioning_ADL_IADL_Ambulation',
 'Prior_Functioning_ADL_IADL_Household_Tasks',
 'Prior_Functioning_ADL_IADL_Self_Care',
 'Prior_Functioning_ADL_IADL_Transfer',
 'Multi_Factor_Fall_Risk_Assessment',
 'Patient_Caregiver_High_Risk_Drug_Educ',
 'Current_Management_Of_Oral_Medications',
 'Current_Management_Of_Injectable_Meds',
 'Prior_Medication_Management_Injectable_Meds',
 'Prior_Medication_Management_Oral_Meds',
 'Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver',
 'Therapy_Need_NA',
 'Therapy_Need_Number_Of_Visits',
 'Plan_Of_Care_Synopsis_At_Risk_For_Falls',
 'Plan_Of_Care_Synopsis_Depression',
 'Plan_Of_Care_Synopsis_Diabetic_Foot_Care',
 'Plan_Of_Care_Synopsis_Pain_Intervention',
 'Plan_Of_Care_Synopsis_Patient_Specific',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention',
 'Emergent_Care_Reason_Acute_Mental_Behavioral',
 'Emergent_Care_Reason_Cardiac_Dysrhythmia',
 'Emergent_Care_Reason_Dehydration_Malnutrition',
 'Emergent_Care_Reason_DVT_Pulmonary_Embolus',
 'Emergent_Care_Reason_GI_Issues',
 'Emergent_Care_Reason_Heart_Failure',
 'Emergent_Care_Hypo_Hyperglycemia',
 'Emergent_Care_Improper_Medication_Administration',
 'Emergent_Care_Reason_Injury_Caused_By_Fall',
 'Emergent_Care_Reason_IV_Catheter_Infection',
 'Emergent_Care_Reason_Myocardial_Infarction',
 'Emergent_Care_Reason_Other_Heart_Disease',
 'Emergent_Care_Reason_Other_Respiratory_Problem',
 'Emergent_Care_Reason_Other_Than_Above',
 'Emergent_Care_Reason_Unknown',
 'Emergent_Care_Reason_Respiratory_Infection',
 'Emergent_Care_Reason_Stroke_CVA_Or_TIA',
 'Emergent_Care_Reason_Uncontrolled_Pain',
 'Emergent_Care_Reason_Urinary_Tract_Infection',
 'Emergent_Care_Reason_Wound_Infection_Or_Deter',
 'Inpatient_Facility_Admitted',
 'Discharge_Disposition',
 'Hospital_Reason_Acute_Mental_Behavioral',
 'Hospital_Reason_Cardiac_Dysrhythmia',
 'Hospital_Reason_Dehydration_Malnutrition',
 'Hospital_Reason_DVT_Pulmonary_Embolus',
 'Hospital_Reason_GI_Issues',
 'Hospital_Reason_Heart_Failure',
 'Hospital_Reason_Hypo_Hyperglycemic',
 'Hospital_Reason_Improper_Medication_Administration',
 'Hospital_Reason_Injury_Caused_By_Fall',
 'Hospital_Reason_IV_Catheter_Infection_Complication',
 'Hospital_Reason_Myocardial_Infarction',
 'Hospital_Reason_Other_Heart_Disease',
 'Hospital_Reason_Other_Respiratory_Problem',
 'Hospital_Reason_Other_Than_Above',
 'Hospital_Reason_Reason_Unknown',
 'Hospital_Reason_Respiratory_Infection',
 'Hospital_Reason_Scheduled_Treatment_Or_Procedure',
 'Hospital_Reason_Stroke_CVA_Or_TIA',
 'Hospital_Reason_Uncontrolled_Pain',
 'Hospital_Reason_Urinary_Tract_Infect',
 'Hospital_Reason_Wound_Infection_Deterioration',
 'Inpatient_Diagnosis_1_ICD_10_C_M',
 'Inpatient_Diagnosis_2_ICD_10_C_M',
 'Inpatient_Diagnosis_3_ICD_10_C_M',
 'Inpatient_Diagnosis_4_ICD_10_C_M',
 'Inpatient_Diagnosis_5_ICD_10_C_M',
 'Inpatient_Diagnosis_6_ICD_10_C_M',
 'Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable',
 'Regimen_Change_Diagnosis_1_ICD_10_C_M',
 'Regimen_Change_Diagnosis_2_ICD_10_C_M',
 'Regimen_Change_Diagnosis_3_ICD_10_C_M',
 'Regimen_Change_Diagnosis_4_ICD_10_C_M',
 'Regimen_Change_Diagnosis_5_ICD_10_C_M',
 'Regimen_Change_Diagnosis_6_ICD_10_C_M',
 'Regimen_Change_Not_Applicable_ICD_10_C_M_Code',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_1_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_2_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_3_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_4_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Other_Diagnosis_Code_5_Severity_ICD_10_C_M',
 'Primary_Optional_Diagnosis_ICD_10_C_M_Code',
 'Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M',
 'Optional_Diagnosis_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Code_5_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M',
 'Risk_for_Hospitalization_Fall_History',
 'Risk_For_Hospitalization_Weight_Loss',
 'Risk_For_Hospitalization_Multiple_Hospitalizations',
 'Risk_For_Hospitalization_Multiple_ER_Visits',
 'Risk_For_Hospitalization_Mental_Emotional_Behavioral',
 'Risk_For_Hospitalization_Difficulty_with_Medical_Instructions',
 'Risk_For_Hospitalization_Taking_Five_or_More_Meds',
 'Risk_For_Hospitalization_Exhaustion',
 'Risk_For_Hospitalization_Other',
 'Risk_For_Hospitalization_None_of_the_Above',
 'Care_Assistance_ADL_Assistance',
 'Care_Assistance_IADL_Assistance',
 'Care_Assistance_Medication_Administration',
 'Care_Assistance_Medical_Procedures_Treatments',
 'Care_Assistance_Management_of_Equipment',
 'Care_Assistance_Supervision_And_Safety',
 'Care_Assistance_Advocacy_Or_Facilitation',
 'Heart_failure_follow_up_phys_ordered_treatmnt',
 'Mobility_Discharge_Goal_Lying_to_Sitting',
 'Mobility_SOC_ROC_Performance_Lying_to_Sitting',
 'HHA_Agency_ID',
 'Active_Diagnoses_Diabetes_Mellitus',
 'Active_Diagnoses_PVD_or_PAD',
 'Height_in_inches',
 'Weight_in_pounds',
 'Number_of_Stage_2_Pressure_Ulcers',
 'Number_of_Stage_2_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_3_Pressure_Ulcers',
 'Number_of_Stage_3_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_4_Pressure_Ulcers',
 'Number_of_Stage_4_pressure_ulcers_at_SOC_ROC',
 'Unstageable_coverage_by_slough_or_eschar',
 'Unstageable_coverage_by_slough_or_eschar_SOC_ROC',
 'Unstageable_suspect_deep_tissue_injury',
 'Unstageable_suspect_deep_tissue_injury_SOC_ROC',
 'Num_unstage_pressure_ulcer_non_remov_dress',
 'Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC',
 'New_worsening_Stage_2',
 'New_worsening_Stage_3',
 'New_worsening_Stage_4',
 'New_worsening_unstageable_non_removable_drs_dv',
 'New_worsening_unstageable_coverage_slough_eschar',
 'New_worsening_unstageable_deep_tissue_injury',
 'Symptoms_in_heart_failure_patients',
 'Heart_failure_follow_up_change_in_care_plan',
 'Heart_failure_follow_up_pt_educ_other_clinical',
 'Heart_failure_follow_up_ER_treatment_advised',
 'Heart_failure_follow_up_no_action',
 'Heart_failure_follow_up_physician_contacted',
 'Drug_regimen_review',
 'Medication_follow_up',
 'Medication_intervention',
 'Patient_caregiver_drug_education_intervention',
 'Emergent_care_use_since_most_recent_SOC_ROC',
 'Intervention_synopsis_diabetic_foot_care',
 'Intervention_synopsis_depression_intervention',
 'Intervention_synopsis_falls_prevention',
 'Intervention_synopsis_monitor_and_mitigate_pain',
 'Intervention_synopsis_prevent_pressure_ulcers',
 'Intervention_synopsis_PU_moist_wound_treatment',
 'AssessmentYear',
 'NumVisits',
 'PrevVisitDate',
 'DaysBetweenVisits',
 'Last_Assessment_Date',
 'Days_Cared_For',
 'Age',
 'ByDiscipline',
 'A00-B99',
 'C00-D49',
 'D50-D89',
 'E00-E89',
 'F01-F99',
 'G00-G99',
 'H00-H59',
 'H60-H95',
 'I00-I99',
 'J00-J99',
 'K00-K95',
 'L00-L99',
 'M00-M99',
 'N00-N99',
 'O00-O9A',
 'P00-P96',
 'Q00-Q99',
 'R00-R99',
 'S00-T88',
 'U00-U85',
 'V00-Y99',
 'Z00-Z99',
 'Assessment_Effective_Date_last',
 'READMISSION']

In [15]:
df = df.drop('Start_of_Care_Date', 'Resumption_of_Care_Date',"Resumption_of_Care_Date_NA", 'Assessment_Effective_Date_last', 'Start_of_Care_Date', 'HHA_Assessment_Internal_ID', 'Submission_Date',  'Branch_Identifier_Number', 'Patient_Birth_Date', 'Date_of_Last_Home_Visit', 'Discharge_Transfer_Death_Date')
df

DataFrame[Beneficiary_ID: string, Assessment_ID: string, Assessment_Effective_Date: date, Calculated_HIPPS_Code: string, Facility_Internal_ID: int, State_ID: string, Submitted_HIPPS_Code: string, Agency_Medicare_Number: string, Branch_State: string, Patient_State: string, Patient_ZIP_Code: int, Gender: string, American_Indian_or_Alaska_Native: int, Asian: int, Black_or_African_American: int, Hispanic_or_Latino: int, Native_Hawiian_or_Pacific_Islander: int, Unknown_Race_Ethnicity: string, White: int, Medicare_Fee_For_Service: int, Medicare_HMO_Managed_Care: int, Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode: string, Discharged_Past_14_Days_From_IPPS: int, Discharged_Past_14_Days_From_IRF: int, Discharged_Past_14_Days_From_LTC: int, Discharged_Past_14_Days_From_LTCH: int, Discharged_Past_14_Days_From_Other: int, Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit: int, Discharged_Past_14_Days_From_SNF_TCU: int, Discharged_Past_14_Days_NA: int, Most_Recent_Inpat_Discharge_Date_UK: int, Most_Recent_Inpatient_Discharge_Date: date, Therapies_In_Home_Enteral_Nutrition: int, Therapies_In_Home_IV_Infusion: int, Therapies_In_Home_None_Above: int, Therapies_In_Home_Parenteral_Nutrition: int, Patient_Overall_Status: string, High_Risk_Factor_Alcohol_Dependency: int, High_Risk_Factor_Drug_Dependency: int, High_Risk_Factor_None_Of_The_Above: int, High_Risk_Factor_Obesity: int, High_Risk_Factor_Smoking: int, High_Risk_Factor_UK: int, Patient_Living_Situation: int, Vision: int, Ability_To_Hear: string, Understanding_Of_Verbal_Content: string, Speech_And_Oral_Expression: int, Formal_Pain_Assessment: int, Frequency_Of_Pain_Interfering_With_Activity: int, Pressure_Ulcer_Assessment: int, Risk_Of_Developing_Pressure_Ulcers: int, Unhealed_Pressure_Ulcer_at_Least_Stage_II: int, Oldest_Stage_II_Onset_Date: date, Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge: string, Status_Of_Most_Problematic_Pressure_Ulcer: string, Current_Number_Of_Stage_I_Pressure_Ulcers: int, Stage_Of_Most_Problematic_Pressure_Ulcer: string, Stasis_Ulcer_Present: int, Current_Number_Of_(Observable)_Stasis_Ulcers: int, Status_Of_Most_Problematic_Stasis_Ulcer: int, Does_This_Patient_Have_A_Surgical_Wound: int, Status_Of_Most_Problematic_Surgical_Wound: int, Skin_Lesion_Or_Open_Wound: int, When_Is_Patient_Dyspneic: int, Resprtry_Treat_At_Home_Airway_Press: int, Resprtry_Treat_At_Home_None: int, Resprtry_Treat_At_Home_Oxygen: int, Resprtry_Treat_At_Home_Ventilator: int, Patient_Treated_For_UTI_Last_14_Days: string, Urinary_Incontinence_Or_Catheter_Presence: int, When_Does_Urinary_Incontinence_Occur: int, Bowel_Incontinence_Frequency: string, Ostomy_For_Bowel_Elimination: int, Cognitive_Functioning: int, When_Confused: string, When_Anxious: string, Depression_Screening: int, Feeling_Down_Depressed_Or_Hopeless: string, Little_Interest_Or_Pleasure_In_Doing_Things: string, Cog_Behavr_Psych_Symp_Delusional: int, Cog_Behavr_Psych_Symp_Impaired_Decision: int, Cog_Behavr_Psych_Symp_Memory_Deficit: int, Cog_Behavr_Psych_Symp_None_Of_The_Above: int, Cog_Behavr_Psych_Symp_Physical_Aggression: int, Cog_Behavr_Psych_Symp_Socially_Inapp: int, Cog_Behavr_Psych_Symp_Verbal_Disruption: int, Frequency_Of_Disruptive_Behavior_Symptoms: int, Receives_Psych_Nursing_Services: int, Current_Grooming: int, Current_Dress_Upper: int, Current_Dress_Lower: int, Current_Bathing: int, Toilet_Transferring: int, Current_Toileting_Hygiene: int, Transferring: int, Ambulation_Locomotion: int, Current_Feeding: int, Current_Preparing_Light_Meals: int, Current_Phone_Use: string, Prior_Functioning_ADL_IADL_Ambulation: int, Prior_Functioning_ADL_IADL_Household_Tasks: int, Prior_Functioning_ADL_IADL_Self_Care: int, Prior_Functioning_ADL_IADL_Transfer: int, Multi_Factor_Fall_Risk_Assessment: int, Patient_Caregiver_High_Risk_Drug_Educ: string, Current_Management_Of_Oral_Medications: string, Current_Management_Of_Injectable_Meds: string, Prior_Medication_Management_Injectable_Meds: string, Prior_Medication_Management_Oral_Meds: string, Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver: string, Therapy_Need_NA: int, Therapy_Need_Number_Of_Visits: int, Plan_Of_Care_Synopsis_At_Risk_For_Falls: string, Plan_Of_Care_Synopsis_Depression: string, Plan_Of_Care_Synopsis_Diabetic_Foot_Care: string, Plan_Of_Care_Synopsis_Pain_Intervention: string, Plan_Of_Care_Synopsis_Patient_Specific: string, Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment: string, Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention: string, Emergent_Care_Reason_Acute_Mental_Behavioral: int, Emergent_Care_Reason_Cardiac_Dysrhythmia: int, Emergent_Care_Reason_Dehydration_Malnutrition: int, Emergent_Care_Reason_DVT_Pulmonary_Embolus: int, Emergent_Care_Reason_GI_Issues: int, Emergent_Care_Reason_Heart_Failure: int, Emergent_Care_Hypo_Hyperglycemia: int, Emergent_Care_Improper_Medication_Administration: int, Emergent_Care_Reason_Injury_Caused_By_Fall: int, Emergent_Care_Reason_IV_Catheter_Infection: int, Emergent_Care_Reason_Myocardial_Infarction: int, Emergent_Care_Reason_Other_Heart_Disease: int, Emergent_Care_Reason_Other_Respiratory_Problem: int, Emergent_Care_Reason_Other_Than_Above: int, Emergent_Care_Reason_Unknown: int, Emergent_Care_Reason_Respiratory_Infection: int, Emergent_Care_Reason_Stroke_CVA_Or_TIA: int, Emergent_Care_Reason_Uncontrolled_Pain: int, Emergent_Care_Reason_Urinary_Tract_Infection: int, Emergent_Care_Reason_Wound_Infection_Or_Deter: int, Inpatient_Facility_Admitted: string, Discharge_Disposition: string, Hospital_Reason_Acute_Mental_Behavioral: int, Hospital_Reason_Cardiac_Dysrhythmia: int, Hospital_Reason_Dehydration_Malnutrition: int, Hospital_Reason_DVT_Pulmonary_Embolus: int, Hospital_Reason_GI_Issues: int, Hospital_Reason_Heart_Failure: int, Hospital_Reason_Hypo_Hyperglycemic: int, Hospital_Reason_Improper_Medication_Administration: int, Hospital_Reason_Injury_Caused_By_Fall: int, Hospital_Reason_IV_Catheter_Infection_Complication: int, Hospital_Reason_Myocardial_Infarction: int, Hospital_Reason_Other_Heart_Disease: int, Hospital_Reason_Other_Respiratory_Problem: int, Hospital_Reason_Other_Than_Above: int, Hospital_Reason_Reason_Unknown: int, Hospital_Reason_Respiratory_Infection: int, Hospital_Reason_Scheduled_Treatment_Or_Procedure: int, Hospital_Reason_Stroke_CVA_Or_TIA: int, Hospital_Reason_Uncontrolled_Pain: int, Hospital_Reason_Urinary_Tract_Infect: int, Hospital_Reason_Wound_Infection_Deterioration: int, Inpatient_Diagnosis_1_ICD_10_C_M: string, Inpatient_Diagnosis_2_ICD_10_C_M: string, Inpatient_Diagnosis_3_ICD_10_C_M: string, Inpatient_Diagnosis_4_ICD_10_C_M: string, Inpatient_Diagnosis_5_ICD_10_C_M: string, Inpatient_Diagnosis_6_ICD_10_C_M: string, Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable: int, Regimen_Change_Diagnosis_1_ICD_10_C_M: string, Regimen_Change_Diagnosis_2_ICD_10_C_M: string, Regimen_Change_Diagnosis_3_ICD_10_C_M: string, Regimen_Change_Diagnosis_4_ICD_10_C_M: string, Regimen_Change_Diagnosis_5_ICD_10_C_M: string, Regimen_Change_Diagnosis_6_ICD_10_C_M: string, Regimen_Change_Not_Applicable_ICD_10_C_M_Code: int, Primary_Diagnosis_ICD_10_C_M_Code: string, Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code: int, Other_Diagnosis_Code_1_ICD_10_C_M: string, Other_Diagnosis_Code_1_Severity_ICD_10_C_M: int, Other_Diagnosis_Code_2_ICD_10_C_M: string, Other_Diagnosis_Code_2_Severity_ICD_10_C_M: int, Other_Diagnosis_Code_3_ICD_10_C_M: string, Other_Diagnosis_Code_3_Severity_ICD_10_C_M: int, Other_Diagnosis_Code_4_ICD_10_C_M: string, Other_Diagnosis_Code_4_Severity_ICD_10_C_M: int, Other_Diagnosis_Code_5_ICD_10_C_M: string, Other_Diagnosis_Code_5_Severity_ICD_10_C_M: int, Primary_Optional_Diagnosis_ICD_10_C_M_Code: string, Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M: string, Optional_Diagnosis_Code_1_ICD_10_C_M: string, Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M: string, Optional_Diagnosis_Code_2_ICD_10_C_M: string, Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M: string, Optional_Diagnosis_Code_3_ICD_10_C_M: string, Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M: string, Optional_Diagnosis_Code_4_ICD_10_C_M: string, Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M: string, Optional_Diagnosis_Code_5_ICD_10_C_M: string, Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M: string, Risk_for_Hospitalization_Fall_History: int, Risk_For_Hospitalization_Weight_Loss: int, Risk_For_Hospitalization_Multiple_Hospitalizations: int, Risk_For_Hospitalization_Multiple_ER_Visits: int, Risk_For_Hospitalization_Mental_Emotional_Behavioral: int, Risk_For_Hospitalization_Difficulty_with_Medical_Instructions: int, Risk_For_Hospitalization_Taking_Five_or_More_Meds: int, Risk_For_Hospitalization_Exhaustion: int, Risk_For_Hospitalization_Other: int, Risk_For_Hospitalization_None_of_the_Above: int, Care_Assistance_ADL_Assistance: int, Care_Assistance_IADL_Assistance: int, Care_Assistance_Medication_Administration: int, Care_Assistance_Medical_Procedures_Treatments: int, Care_Assistance_Management_of_Equipment: int, Care_Assistance_Supervision_And_Safety: int, Care_Assistance_Advocacy_Or_Facilitation: int, Heart_failure_follow_up_phys_ordered_treatmnt: int, Mobility_Discharge_Goal_Lying_to_Sitting: string, Mobility_SOC_ROC_Performance_Lying_to_Sitting: string, HHA_Agency_ID: string, Active_Diagnoses_Diabetes_Mellitus: string, Active_Diagnoses_PVD_or_PAD: string, Height_in_inches: string, Weight_in_pounds: string, Number_of_Stage_2_Pressure_Ulcers: int, Number_of_Stage_2_pressure_ulcers_at_SOC_ROC: int, Number_of_Stage_3_Pressure_Ulcers: int, Number_of_Stage_3_pressure_ulcers_at_SOC_ROC: int, Number_of_Stage_4_Pressure_Ulcers: int, Number_of_Stage_4_pressure_ulcers_at_SOC_ROC: int, Unstageable_coverage_by_slough_or_eschar: int, Unstageable_coverage_by_slough_or_eschar_SOC_ROC: int, Unstageable_suspect_deep_tissue_injury: int, Unstageable_suspect_deep_tissue_injury_SOC_ROC: int, Num_unstage_pressure_ulcer_non_remov_dress: int, Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC: int, New_worsening_Stage_2: string, New_worsening_Stage_3: string, New_worsening_Stage_4: string, New_worsening_unstageable_non_removable_drs_dv: string, New_worsening_unstageable_coverage_slough_eschar: string, New_worsening_unstageable_deep_tissue_injury: string, Symptoms_in_heart_failure_patients: string, Heart_failure_follow_up_change_in_care_plan: int, Heart_failure_follow_up_pt_educ_other_clinical: int, Heart_failure_follow_up_ER_treatment_advised: int, Heart_failure_follow_up_no_action: int, Heart_failure_follow_up_physician_contacted: int, Drug_regimen_review: string, Medication_follow_up: string, Medication_intervention: string, Patient_caregiver_drug_education_intervention: string, Emergent_care_use_since_most_recent_SOC_ROC: string, Intervention_synopsis_diabetic_foot_care: string, Intervention_synopsis_depression_intervention: string, Intervention_synopsis_falls_prevention: string, Intervention_synopsis_monitor_and_mitigate_pain: string, Intervention_synopsis_prevent_pressure_ulcers: string, Intervention_synopsis_PU_moist_wound_treatment: string, AssessmentYear: int, NumVisits: bigint, PrevVisitDate: date, DaysBetweenVisits: int, Last_Assessment_Date: date, Days_Cared_For: int, Age: double, ByDiscipline: string, A00-B99: int, C00-D49: int, D50-D89: int, E00-E89: int, F01-F99: int, G00-G99: int, H00-H59: int, H60-H95: int, I00-I99: int, J00-J99: int, K00-K95: int, L00-L99: int, M00-M99: int, N00-N99: int, O00-O9A: int, P00-P96: int, Q00-Q99: int, R00-R99: int, S00-T88: int, U00-U85: int, V00-Y99: int, Z00-Z99: int, READMISSION: int]

In [16]:
# ICD diagnosis columns
icd_cols = [
    "Inpatient_Diagnosis_1_ICD_10_C_M","Inpatient_Diagnosis_2_ICD_10_C_M","Inpatient_Diagnosis_3_ICD_10_C_M",
    "Inpatient_Diagnosis_4_ICD_10_C_M","Inpatient_Diagnosis_5_ICD_10_C_M","Inpatient_Diagnosis_6_ICD_10_C_M",
    "Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable",
    "Primary_Diagnosis_ICD_10_C_M_Code","Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code",
    "Primary_Optional_Diagnosis_ICD_10_C_M_Code","Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M"
]

# ICD ranges for each condition
ICD_CLASS_MAP = {
    "Diabetes": ["E00-E89", "R00-R99", "Z00-Z99"],
    "HeartFailure": ["I00-I99"],
    "Hypertension": ["I00-I99"],
    "RenalFailure": ["N00-N99", "E00-E89", "I00-I99"]
}

# parse ranges
def parse_range(r):
    start, end = r.split('-')
    return (
        start[0], int(start[1:]),
        end[0], int(end[1:])
    )

PARSED_RANGES = {
    cond: [parse_range(r) for r in ranges]
    for cond, ranges in ICD_CLASS_MAP.items()
}

# fixed function
def code_in_ranges(code, range_list):
    if code is None:
        return False

    # convert to string safely
    code = str(code).strip()
    if code == "":
        return False

    letter = code[0]

    # extract leading digits
    num_str = ''.join([c for c in code[1:] if c.isdigit()])
    if num_str == "":
        return False
    num = int(num_str)

    for (start_letter, start_num, end_letter, end_num) in range_list:
        if start_letter <= letter <= end_letter and start_num <= num <= end_num:
            return True
    return False

# classify patient
def classify_conditions(*codes):
    results = {cond: 0 for cond in PARSED_RANGES}

    for code in codes:
        for cond, ranges in PARSED_RANGES.items():
            if code_in_ranges(code, ranges):
                results[cond] = 1

    return (results["Diabetes"], results["HeartFailure"],
            results["Hypertension"], results["RenalFailure"])

# create UDF
classify_udf = F.udf(classify_conditions, "struct<diabetes:int,heartfailure:int,hypertension:int,renalfailure:int>")

# apply UDF
df = df.withColumn("conditions", classify_udf(*[F.col(c) for c in icd_cols]))

# expand struct into separate columns
df = df \
    .withColumn("is_diabetes", F.col("conditions.diabetes")) \
    .withColumn("is_heart_failure", F.col("conditions.heartfailure")) \
    .withColumn("is_hypertension", F.col("conditions.hypertension")) \
    .withColumn("is_renal_failure", F.col("conditions.renalfailure")) \
    .drop("conditions")

In [17]:
df.columns

['Beneficiary_ID',
 'Assessment_ID',
 'Assessment_Effective_Date',
 'Calculated_HIPPS_Code',
 'Facility_Internal_ID',
 'State_ID',
 'Submitted_HIPPS_Code',
 'Agency_Medicare_Number',
 'Branch_State',
 'Patient_State',
 'Patient_ZIP_Code',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'Medicare_Fee_For_Service',
 'Medicare_HMO_Managed_Care',
 'Medicare_HHA_pymnt_episode_asmt_case_mix_grp_early_later_episode',
 'Discharged_Past_14_Days_From_IPPS',
 'Discharged_Past_14_Days_From_IRF',
 'Discharged_Past_14_Days_From_LTC',
 'Discharged_Past_14_Days_From_LTCH',
 'Discharged_Past_14_Days_From_Other',
 'Discharged_Past_14_Days_From_Psychiatric_Hospital_Or_Unit',
 'Discharged_Past_14_Days_From_SNF_TCU',
 'Discharged_Past_14_Days_NA',
 'Most_Recent_Inpat_Discharge_Date_UK',
 'Most_Recent_Inpatient_Discharge_Date',
 'Therapies_In_Home_Enteral_Nutrition',
 'Therapies_In_Home_IV_Infusion',
 'Therapies_In_Home_None_Above',
 'Therapies_In_Home_Parenteral_Nutrition',
 'Patient_Overall_Status',
 'High_Risk_Factor_Alcohol_Dependency',
 'High_Risk_Factor_Drug_Dependency',
 'High_Risk_Factor_None_Of_The_Above',
 'High_Risk_Factor_Obesity',
 'High_Risk_Factor_Smoking',
 'High_Risk_Factor_UK',
 'Patient_Living_Situation',
 'Vision',
 'Ability_To_Hear',
 'Understanding_Of_Verbal_Content',
 'Speech_And_Oral_Expression',
 'Formal_Pain_Assessment',
 'Frequency_Of_Pain_Interfering_With_Activity',
 'Pressure_Ulcer_Assessment',
 'Risk_Of_Developing_Pressure_Ulcers',
 'Unhealed_Pressure_Ulcer_at_Least_Stage_II',
 'Oldest_Stage_II_Onset_Date',
 'Status_Oldst_Stg_2_Pressure_Ulcer_At_Discharge',
 'Status_Of_Most_Problematic_Pressure_Ulcer',
 'Current_Number_Of_Stage_I_Pressure_Ulcers',
 'Stage_Of_Most_Problematic_Pressure_Ulcer',
 'Stasis_Ulcer_Present',
 'Current_Number_Of_(Observable)_Stasis_Ulcers',
 'Status_Of_Most_Problematic_Stasis_Ulcer',
 'Does_This_Patient_Have_A_Surgical_Wound',
 'Status_Of_Most_Problematic_Surgical_Wound',
 'Skin_Lesion_Or_Open_Wound',
 'When_Is_Patient_Dyspneic',
 'Resprtry_Treat_At_Home_Airway_Press',
 'Resprtry_Treat_At_Home_None',
 'Resprtry_Treat_At_Home_Oxygen',
 'Resprtry_Treat_At_Home_Ventilator',
 'Patient_Treated_For_UTI_Last_14_Days',
 'Urinary_Incontinence_Or_Catheter_Presence',
 'When_Does_Urinary_Incontinence_Occur',
 'Bowel_Incontinence_Frequency',
 'Ostomy_For_Bowel_Elimination',
 'Cognitive_Functioning',
 'When_Confused',
 'When_Anxious',
 'Depression_Screening',
 'Feeling_Down_Depressed_Or_Hopeless',
 'Little_Interest_Or_Pleasure_In_Doing_Things',
 'Cog_Behavr_Psych_Symp_Delusional',
 'Cog_Behavr_Psych_Symp_Impaired_Decision',
 'Cog_Behavr_Psych_Symp_Memory_Deficit',
 'Cog_Behavr_Psych_Symp_None_Of_The_Above',
 'Cog_Behavr_Psych_Symp_Physical_Aggression',
 'Cog_Behavr_Psych_Symp_Socially_Inapp',
 'Cog_Behavr_Psych_Symp_Verbal_Disruption',
 'Frequency_Of_Disruptive_Behavior_Symptoms',
 'Receives_Psych_Nursing_Services',
 'Current_Grooming',
 'Current_Dress_Upper',
 'Current_Dress_Lower',
 'Current_Bathing',
 'Toilet_Transferring',
 'Current_Toileting_Hygiene',
 'Transferring',
 'Ambulation_Locomotion',
 'Current_Feeding',
 'Current_Preparing_Light_Meals',
 'Current_Phone_Use',
 'Prior_Functioning_ADL_IADL_Ambulation',
 'Prior_Functioning_ADL_IADL_Household_Tasks',
 'Prior_Functioning_ADL_IADL_Self_Care',
 'Prior_Functioning_ADL_IADL_Transfer',
 'Multi_Factor_Fall_Risk_Assessment',
 'Patient_Caregiver_High_Risk_Drug_Educ',
 'Current_Management_Of_Oral_Medications',
 'Current_Management_Of_Injectable_Meds',
 'Prior_Medication_Management_Injectable_Meds',
 'Prior_Medication_Management_Oral_Meds',
 'Frequency_Of_ADL_Or_IADL_Assistance_From_Caregiver',
 'Therapy_Need_NA',
 'Therapy_Need_Number_Of_Visits',
 'Plan_Of_Care_Synopsis_At_Risk_For_Falls',
 'Plan_Of_Care_Synopsis_Depression',
 'Plan_Of_Care_Synopsis_Diabetic_Foot_Care',
 'Plan_Of_Care_Synopsis_Pain_Intervention',
 'Plan_Of_Care_Synopsis_Patient_Specific',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Moist_Treatment',
 'Plan_Of_Care_Synopsis_Pressure_Ulcer_Prevention',
 'Emergent_Care_Reason_Acute_Mental_Behavioral',
 'Emergent_Care_Reason_Cardiac_Dysrhythmia',
 'Emergent_Care_Reason_Dehydration_Malnutrition',
 'Emergent_Care_Reason_DVT_Pulmonary_Embolus',
 'Emergent_Care_Reason_GI_Issues',
 'Emergent_Care_Reason_Heart_Failure',
 'Emergent_Care_Hypo_Hyperglycemia',
 'Emergent_Care_Improper_Medication_Administration',
 'Emergent_Care_Reason_Injury_Caused_By_Fall',
 'Emergent_Care_Reason_IV_Catheter_Infection',
 'Emergent_Care_Reason_Myocardial_Infarction',
 'Emergent_Care_Reason_Other_Heart_Disease',
 'Emergent_Care_Reason_Other_Respiratory_Problem',
 'Emergent_Care_Reason_Other_Than_Above',
 'Emergent_Care_Reason_Unknown',
 'Emergent_Care_Reason_Respiratory_Infection',
 'Emergent_Care_Reason_Stroke_CVA_Or_TIA',
 'Emergent_Care_Reason_Uncontrolled_Pain',
 'Emergent_Care_Reason_Urinary_Tract_Infection',
 'Emergent_Care_Reason_Wound_Infection_Or_Deter',
 'Inpatient_Facility_Admitted',
 'Discharge_Disposition',
 'Hospital_Reason_Acute_Mental_Behavioral',
 'Hospital_Reason_Cardiac_Dysrhythmia',
 'Hospital_Reason_Dehydration_Malnutrition',
 'Hospital_Reason_DVT_Pulmonary_Embolus',
 'Hospital_Reason_GI_Issues',
 'Hospital_Reason_Heart_Failure',
 'Hospital_Reason_Hypo_Hyperglycemic',
 'Hospital_Reason_Improper_Medication_Administration',
 'Hospital_Reason_Injury_Caused_By_Fall',
 'Hospital_Reason_IV_Catheter_Infection_Complication',
 'Hospital_Reason_Myocardial_Infarction',
 'Hospital_Reason_Other_Heart_Disease',
 'Hospital_Reason_Other_Respiratory_Problem',
 'Hospital_Reason_Other_Than_Above',
 'Hospital_Reason_Reason_Unknown',
 'Hospital_Reason_Respiratory_Infection',
 'Hospital_Reason_Scheduled_Treatment_Or_Procedure',
 'Hospital_Reason_Stroke_CVA_Or_TIA',
 'Hospital_Reason_Uncontrolled_Pain',
 'Hospital_Reason_Urinary_Tract_Infect',
 'Hospital_Reason_Wound_Infection_Deterioration',
 'Inpatient_Diagnosis_1_ICD_10_C_M',
 'Inpatient_Diagnosis_2_ICD_10_C_M',
 'Inpatient_Diagnosis_3_ICD_10_C_M',
 'Inpatient_Diagnosis_4_ICD_10_C_M',
 'Inpatient_Diagnosis_5_ICD_10_C_M',
 'Inpatient_Diagnosis_6_ICD_10_C_M',
 'Inpatient_Diagnosis_ICD_10_C_M_Not_Applicable',
 'Regimen_Change_Diagnosis_1_ICD_10_C_M',
 'Regimen_Change_Diagnosis_2_ICD_10_C_M',
 'Regimen_Change_Diagnosis_3_ICD_10_C_M',
 'Regimen_Change_Diagnosis_4_ICD_10_C_M',
 'Regimen_Change_Diagnosis_5_ICD_10_C_M',
 'Regimen_Change_Diagnosis_6_ICD_10_C_M',
 'Regimen_Change_Not_Applicable_ICD_10_C_M_Code',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Primary_Diagnosis_Severity_Rating_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_1_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_2_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_3_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_4_Severity_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Other_Diagnosis_Code_5_Severity_ICD_10_C_M',
 'Primary_Optional_Diagnosis_ICD_10_C_M_Code',
 'Primary_Optional_Diagnosis_Multiple_Codes_ICD_10_C_M',
 'Optional_Diagnosis_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_1_ICD_10_C_M',
 'Optional_Diagnosis_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_2_ICD_10_C_M',
 'Optional_Diagnosis_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_3_ICD_10_C_M',
 'Optional_Diagnosis_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_4_ICD_10_C_M',
 'Optional_Diagnosis_Code_5_ICD_10_C_M',
 'Optional_Diagnosis_Multiple_Code_5_ICD_10_C_M',
 'Risk_for_Hospitalization_Fall_History',
 'Risk_For_Hospitalization_Weight_Loss',
 'Risk_For_Hospitalization_Multiple_Hospitalizations',
 'Risk_For_Hospitalization_Multiple_ER_Visits',
 'Risk_For_Hospitalization_Mental_Emotional_Behavioral',
 'Risk_For_Hospitalization_Difficulty_with_Medical_Instructions',
 'Risk_For_Hospitalization_Taking_Five_or_More_Meds',
 'Risk_For_Hospitalization_Exhaustion',
 'Risk_For_Hospitalization_Other',
 'Risk_For_Hospitalization_None_of_the_Above',
 'Care_Assistance_ADL_Assistance',
 'Care_Assistance_IADL_Assistance',
 'Care_Assistance_Medication_Administration',
 'Care_Assistance_Medical_Procedures_Treatments',
 'Care_Assistance_Management_of_Equipment',
 'Care_Assistance_Supervision_And_Safety',
 'Care_Assistance_Advocacy_Or_Facilitation',
 'Heart_failure_follow_up_phys_ordered_treatmnt',
 'Mobility_Discharge_Goal_Lying_to_Sitting',
 'Mobility_SOC_ROC_Performance_Lying_to_Sitting',
 'HHA_Agency_ID',
 'Active_Diagnoses_Diabetes_Mellitus',
 'Active_Diagnoses_PVD_or_PAD',
 'Height_in_inches',
 'Weight_in_pounds',
 'Number_of_Stage_2_Pressure_Ulcers',
 'Number_of_Stage_2_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_3_Pressure_Ulcers',
 'Number_of_Stage_3_pressure_ulcers_at_SOC_ROC',
 'Number_of_Stage_4_Pressure_Ulcers',
 'Number_of_Stage_4_pressure_ulcers_at_SOC_ROC',
 'Unstageable_coverage_by_slough_or_eschar',
 'Unstageable_coverage_by_slough_or_eschar_SOC_ROC',
 'Unstageable_suspect_deep_tissue_injury',
 'Unstageable_suspect_deep_tissue_injury_SOC_ROC',
 'Num_unstage_pressure_ulcer_non_remov_dress',
 'Num_unstage_pressure_ulcer_non_remov_dress_SOC_ROC',
 'New_worsening_Stage_2',
 'New_worsening_Stage_3',
 'New_worsening_Stage_4',
 'New_worsening_unstageable_non_removable_drs_dv',
 'New_worsening_unstageable_coverage_slough_eschar',
 'New_worsening_unstageable_deep_tissue_injury',
 'Symptoms_in_heart_failure_patients',
 'Heart_failure_follow_up_change_in_care_plan',
 'Heart_failure_follow_up_pt_educ_other_clinical',
 'Heart_failure_follow_up_ER_treatment_advised',
 'Heart_failure_follow_up_no_action',
 'Heart_failure_follow_up_physician_contacted',
 'Drug_regimen_review',
 'Medication_follow_up',
 'Medication_intervention',
 'Patient_caregiver_drug_education_intervention',
 'Emergent_care_use_since_most_recent_SOC_ROC',
 'Intervention_synopsis_diabetic_foot_care',
 'Intervention_synopsis_depression_intervention',
 'Intervention_synopsis_falls_prevention',
 'Intervention_synopsis_monitor_and_mitigate_pain',
 'Intervention_synopsis_prevent_pressure_ulcers',
 'Intervention_synopsis_PU_moist_wound_treatment',
 'AssessmentYear',
 'NumVisits',
 'PrevVisitDate',
 'DaysBetweenVisits',
 'Last_Assessment_Date',
 'Days_Cared_For',
 'Age',
 'ByDiscipline',
 'A00-B99',
 'C00-D49',
 'D50-D89',
 'E00-E89',
 'F01-F99',
 'G00-G99',
 'H00-H59',
 'H60-H95',
 'I00-I99',
 'J00-J99',
 'K00-K95',
 'L00-L99',
 'M00-M99',
 'N00-N99',
 'O00-O9A',
 'P00-P96',
 'Q00-Q99',
 'R00-R99',
 'S00-T88',
 'U00-U85',
 'V00-Y99',
 'Z00-Z99',
 'READMISSION',
 'is_diabetes',
 'is_heart_failure',
 'is_hypertension',
 'is_renal_failure']

In [18]:
filtered_df = df.filter(F.col("STATE_ID") == "TX")

# Filter by top feats (BIGDATA-23)

In [19]:
cols = ['Beneficiary_ID', 'Assessment_Effective_Date', 'Submitted_HIPPS_Code', 'Facility_Internal_ID','Age','Gender',
        'American_Indian_or_Alaska_Native','Asian','Black_or_African_American', 'Hispanic_or_Latino', 
        'Native_Hawiian_or_Pacific_Islander', 'Unknown_Race_Ethnicity', 'White',  'ByDiscipline', 'DaysBetweenVisits',
        'Days_Cared_For', 'READMISSION', 'Patient_ZIP_Code', 'Agency_Medicare_Number', 'Primary_Diagnosis_ICD_10_C_M_Code',
        'Other_Diagnosis_Code_1_ICD_10_C_M', 'Other_Diagnosis_Code_2_ICD_10_C_M',
        'Other_Diagnosis_Code_3_ICD_10_C_M', 'Other_Diagnosis_Code_4_ICD_10_C_M',
        'Other_Diagnosis_Code_5_ICD_10_C_M', 'Weight_in_pounds', 'Height_in_inches', 'is_diabetes', 'is_heart_failure',
        'is_hypertension', 'is_renal_failure']
df_topFeats = filtered_df.select(cols).dropDuplicates(subset=['Beneficiary_ID','READMISSION'])

In [20]:
df_topFeats = df_topFeats.withColumn("Weight_in_pounds", col("Weight_in_pounds").cast("double"))
df_topFeats = df_topFeats.withColumn("Height_in_inches", col("Height_in_inches").cast("double"))

In [21]:
# Calculate BMI
df_topFeats = df_topFeats.withColumn(
    "BMI", ceil((col("Weight_in_pounds") / (col("Height_in_inches") ** 2)) * lit(704.5))
)

df_topFeats = df_topFeats.fillna({"BMI": 0})# Replace infinite values and NaN with 0
df_topFeats = df_topFeats.withColumn("BMI", col("BMI").cast("int"))# Convert BMI to integer
df_topFeats = df_topFeats.withColumn("Age", col("Age").cast("int"))# Convert Age to floor value

# Categorize BMI
df_topFeats = df_topFeats.withColumn(
    "BMI_Category",
    when(col("BMI") < 18.5, lit("Underweight"))
    .when((col("BMI") >= 18.5) & (col("BMI") < 24.9), lit("Normal weight"))
    .when((col("BMI") >= 25) & (col("BMI") < 29.9), lit("Overweight"))
    .when((col("BMI") >= 30) & (col("BMI") < 34.9), lit("Obese-Class1"))
    .when((col("BMI") >= 35) & (col("BMI") < 39.9), lit("Obese-Class2"))
    .otherwise(lit("Obese-Class3")),
)

df_topFeats = df_topFeats.drop("M1060_WEIGHT", "M1060_HEIGHT")
df_topFeats.show()

In [22]:
df_topFeats.columns

['Beneficiary_ID',
 'Assessment_Effective_Date',
 'Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Age',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'ByDiscipline',
 'DaysBetweenVisits',
 'Days_Cared_For',
 'READMISSION',
 'Patient_ZIP_Code',
 'Agency_Medicare_Number',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Weight_in_pounds',
 'Height_in_inches',
 'is_diabetes',
 'is_heart_failure',
 'is_hypertension',
 'is_renal_failure',
 'BMI',
 'BMI_Category']

In [23]:
df_pandas = df_topFeats.toPandas()

In [24]:
df_pandas.columns

Index(['Beneficiary_ID', 'Assessment_Effective_Date', 'Submitted_HIPPS_Code',
       'Facility_Internal_ID', 'Age', 'Gender',
       'American_Indian_or_Alaska_Native', 'Asian',
       'Black_or_African_American', 'Hispanic_or_Latino',
       'Native_Hawiian_or_Pacific_Islander', 'Unknown_Race_Ethnicity', 'White',
       'ByDiscipline', 'DaysBetweenVisits', 'Days_Cared_For', 'READMISSION',
       'Patient_ZIP_Code', 'Agency_Medicare_Number',
       'Primary_Diagnosis_ICD_10_C_M_Code',
       'Other_Diagnosis_Code_1_ICD_10_C_M',
       'Other_Diagnosis_Code_2_ICD_10_C_M',
       'Other_Diagnosis_Code_3_ICD_10_C_M',
       'Other_Diagnosis_Code_4_ICD_10_C_M',
       'Other_Diagnosis_Code_5_ICD_10_C_M', 'Weight_in_pounds',
       'Height_in_inches', 'is_diabetes', 'is_heart_failure',
       'is_hypertension', 'is_renal_failure', 'BMI', 'BMI_Category'],
      dtype='object')

In [25]:
sdoh_geo = pd.read_csv('data/texas_sdoh_tract_georef_census.csv')
sdoh_geo

,zip,primary_city,area_codes,COUNTY_NAME,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,COUNTYFIPS,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ANY,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_CIVIL_NONINST_POP_POV,ACS_TOT_CIVIL_POP_POV,ACS_TOT_POP_POV
0,75763,Frankston,"430, 903",Anderson,57922.0,20131.0,18615.0,32.14,39307.0,67.86,48001,7.841667,32.505833,4.401667,38.8575,16.396667,0.484167,44.747500,21.754167,43.486667,34.760000,1.988333,45.035833,67.546667,12.244167,52.398333,13.515000,0.416667,67.963333,2.157500,11.7675,21.545833,6.0100,0.0,61.189167,4.223333,16.269167,72.360000,12.733333,46.878333,0.6250,10.084167,30.835000,37.776667,20.465833,33.424167,23.509167,29.446667,10.115833,16.695833,103.250000,19.629167,32.141667,21.355000,26.874167,27.555000,10.730833,4.674167,6.685833,12.410833,4.845833,2.404167,18.850000,4.595833,21.844167,53.496667,20.064167,18.616667,9.615,22.0325,21.848333,22.510833,0.0,10.224167,9.229167,2.745,3700.166667,2778.083333,3700.166667
1,75779,Neches,"430, 903",Anderson,57922.0,20131.0,18615.0,32.14,39307.0,67.86,48001,7.841667,32.505833,4.401667,38.8575,16.396667,0.484167,44.747500,21.754167,43.486667,34.760000,1.988333,45.035833,67.546667,12.244167,52.398333,13.515000,0.416667,67.963333,2.157500,11.7675,21.545833,6.0100,0.0,61.189167,4.223333,16.269167,72.360000,12.733333,46.878333,0.6250,10.084167,30.835000,37.776667,20.465833,33.424167,23.509167,29.446667,10.115833,16.695833,103.250000,19.629167,32.141667,21.355000,26.874167,27.555000,10.730833,4.674167,6.685833,12.410833,4.845833,2.404167,18.850000,4.595833,21.844167,53.496667,20.064167,18.616667,9.615,22.0325,21.848333,22.510833,0.0,10.224167,9.229167,2.745,3700.166667,2778.083333,3700.166667
2,75801,Palestine,"430, 903",Anderson,57922.0,20131.0,18615.0,32.14,39307.0,67.86,48001,7.841667,32.505833,4.401667,38.8575,16.396667,0.484167,44.747500,21.754167,43.486667,34.760000,1.988333,45.035833,67.546667,12.244167,52.398333,13.515000,0.416667,67.963333,2.157500,11.7675,21.545833,6.0100,0.0,61.189167,4.223333,16.269167,72.360000,12.733333,46.878333,0.6250,10.084167,30.835000,37.776667,20.465833,33.424167,23.509167,29.446667,10.115833,16.695833,103.250000,19.629167,32.141667,21.355000,26.874167,27.555000,10.730833,4.674167,6.685833,12.410833,4.845833,2.404167,18.850000,4.595833,21.844167,53.496667,20.064167,18.616667,9.615,22.0325,21.848333,22.510833,0.0,10.224167,9.229167,2.745,3700.166667,2778.083333,3700.166667
3,75802,Palestine,903,Anderson,57922.0,20131.0,18615.0,32.14,39307.0,67.86,48001,7.841667,32.505833,4.401667,38.8575,16.396667,0.484167,44.747500,21.754167,43.486667,34.760000,1.988333,45.035833,67.546667,12.244167,52.398333,13.515000,0.416667,67.963333,2.157500,11.7675,21.545833,6.0100,0.0,61.189167,4.223333,16.269167,72.360000,12.733333,46.878333,0.6250,10.084167,30.835000,37.776667,20.465833,33.424167,23.509167,29.446667,10.115833,16.695833,103.250000,19.629167,32.141667,21.355000,26.874167,27.555000,10.730833,4.674167,6.685833,12.410833,4.845833,2.404167,18.850000,4.595833,21.844167,53.496667,20.064167,18.616667,9.615,22.0325,21.848333,22.510833,0.0,10.224167,9.229167,2.745,3700.166667,2778.083333,3700.166667
4,75803,Palestine,"430, 903",Anderson,57922.0,20131.0,18615.0,32.14,39307.0,67.86,48001,7.841667,32.505833,4.401667,38.8575,16.396667,0.484167,44.747500,21.754167,43.486667,34.760000,1.988333,45.035833,67.546667,12.244167,52.398333,13.515000,0.416667,67.963333,2.157500,11.7675,21.545833,6.0100,0.0,61.189167,4.223333,16.269167,72.360000,12.733333,46.878333,0.6250,10.084167,30.835000,37.776667,20.465833,33.424167,23.509167,29.446667,10.115833,16.695833,103.250000,19.629167,32.141667,21.355000,26.874167,27.555000,10.730833,4.674167,6.685833,12.410833,4.845833,2.404167,18.850000,4.595833,21.844167,53.496667,20.064167,18.616667,9.615,22.0325,21.848333,22.510833,0.0,10.224167,9.229167,2.745,3700.166667,2778.083333,3700.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,78076,Zapata,"361, 830, 956",Zapata,13889.0,6159.0,10942.0,78.78,2947.0,21.22,48505,11.126667,22.873333,1.083333,30.1600,34.751667,0.000000,35.083333,11.053333,34.393333,54.553333,30.295000,51.181667,62.891667,22.856667,38.301667,7.218333,0.000000,62.891667,0.428333,20.1000,36.680000,0.0000,0.0,45.706667,4.481667,8.993333,74.046667,24.921667,43.023333,0.1500,13.645000,48.273333,50.763333,0.000000,32.570000,27.293333,31.595000,15.331667,32.753333,78.666667,17.538333,27.831667,14.203333,40.430000,23.733333,24.021667,15.036667,14.236667,24.021667,14.911667,2.531667,21.328333,8.213333,20.481667,42.033333,29.276667,0.000000,0.000,0.0000,29.555000,20.133333,0.0,39.231667,26.091667,0.000,2341.666667,1575.000000,2341.666667
2644,78564,Lopeno,956,Zapata,13889.0,6159.0,10942.0,78.78,2947.0,21.22,48505,11.126667,22.873333,1.083333,30.1600,34.751667,0.000000,35.083333,11.053333,34.393333,54.553333,30.295000,51.181667,62.891667,22.856667,38.301667,7.218333,0.000000,62.891667,0.428333,20.1000,36.680000,0.0000,0.0,45.706667,4.481667,8.993333,74.046667,24.921667,43.023333,0.1500,13.645000,48.273333,50.763333,0.000000,32.570000,27.293333,31.595000,15.331667,32.753333,78.666667,17.538333,27.831667,14.203333,40.430000,23.733333,24.021667,15.036667,14.236667,24.021667,14.911667,2.531667,21.328333,8.213333,20.481667,42.033333,29.276667,0.000000,0.000,0.0000,29.555000,20.133333,0.0,39.231667,26.091667,0.000,2341.666667,1575.000000,2341.666667
2645,78829,Batesville,830,Zavala,9670.0,3920.0,6709.0,69.38,2961.0,30.62,48507,5.672500,26.702500,3.967500,33.6425,30.020000,0.000000,36.342500,14.482500,39.522500,45.992500,9.212500,43.125000,61.500000,27.665000,27.835000,11.195000,0.000000,61.500000,6.352500,13.6900,32.147500,0.3075,0.0,41.582500,4.602500,9.560000,79.380000,35.857500,36.980000,1.6725,22.710000,65.415000,35.462500,11.467500,53.070000,14.712500,35.415000,10.497500,28.812500,176.000000,13.627500,22.467500,12.490000,51.415000,61.387500,30.865000,22.857500,10.517500,31.452500,19.097500,4.167500,28.587500,7.715000,17.032500,34.957500,40.295000,0.000000,0.000,25.0000,36.837500,15.837500,0.0,8.937500,43.810000,25.000,2950.250000,2084.250000,2950.250000
2646,78839,Crystal City,830,Zavala,9670.0,3920.0,6709.0,69.38,2961.0,30.62,48507,5.672500,26.702500,3.967500,33.6425,30.020000,0.000000,36.342500,14.482500,39.522500,45.992500,9.212500,43.125000,61.500000,27.665000,27.835000,11.195000,0.000000,61.500000,6.352500,13.6900,32.147500,0.3075,0.0,41.582500,4.602500,9.560000,79.380000,35.857500,36.980000,1.6725,22.710000,65.415000,35.462500,11.467500,53.070000,14.712500,35.415000,10.497500,28.812500,176.000000,13.627500,22.467500,12.490000,51.415000,61.387500,30.865000,22.857500,10.517500,31.452500,19.097500,4.167500,28.587500,7.715000,17.032500,34.957500,40.295000,0.000000,0.000,25.0000,36.837500,15.837500,0.0,8.937500,43.810000,25.000,2950.250000,2084.250000,2950.250000
2647,78872,La Pryor,830,Zavala,9670.0,3920.0,6709.0,69.38,2961.0,30.62,48507,5.672500,26.702500,3.967500,33.6425,30.020000,0.000000,36.342500,14.482500,39.522500,45.992500,9.212500,43.125000,61.500000,27.665000,27.835000,11.195000,0.000000,61.500000,6.352500,13.6900,32.147500,0.3075,0.0,41.582500,4.602500,9.560000,79.380000,35.857500,36.980000,1.6725,22.710000,65.415000,35.462500,11.467500,53.070000,14.712500,35.415000,10.497500,28.812500,176.000000,13.627500,22.467500,12.490000,51.415000,61.387500,30.865000,22.857500,10.517500,31.452500,19.097500,4.167500,28.587500,7.715000,17.032500,34.957500,40.295000,0.000000,0.000,25.0000,36.837500,15.837500,0.0,8.937500,43.810000,25.000,2950.250000,2084.250000,2950.250000

In [26]:
zip_county_combinations = sdoh_geo.groupby(["zip", "COUNTY_NAME"]).size().reset_index(name="Count")
zip_county_combinations

        zip COUNTY_NAME  Count
0     73301      Travis      1
1     73344      Travis      1
2     73960     Sherman      1
3     75001      Dallas      1
4     75002      Collin      1
...     ...         ...    ...
2643  88587     El Paso      1
2644  88588     El Paso      1
2645  88589     El Paso      1
2646  88590     El Paso      1
2647  88595     El Paso      1

[2648 rows x 3 columns]

In [27]:
zip_count_per_county = sdoh_geo.groupby("COUNTY_NAME")["zip"].nunique().reset_index()
zip_count_per_county.columns = ["County", "Zip Count"]
zip_count_per_county

       County  Zip Count
0    Anderson         13
1     Andrews          1
2    Angelina          9
3     Aransas          3
4      Archer          5
..        ...        ...
249      Wood          7
250    Yoakum          2
251     Young          5
252    Zapata          3
253    Zavala          3

[254 rows x 2 columns]

In [28]:
df_merged= df_pandas.merge(
    sdoh_geo, 
    left_on="Patient_ZIP_Code", 
    right_on="zip", 
    how="inner"
).drop(columns=["Patient_ZIP_Code", "zip"]).drop_duplicates()
df_merged

,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,Unknown_Race_Ethnicity,White,ByDiscipline,DaysBetweenVisits,Days_Cared_For,READMISSION,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code,Other_Diagnosis_Code_1_ICD_10_C_M,Other_Diagnosis_Code_2_ICD_10_C_M,Other_Diagnosis_Code_3_ICD_10_C_M,Other_Diagnosis_Code_4_ICD_10_C_M,Other_Diagnosis_Code_5_ICD_10_C_M,Weight_in_pounds,Height_in_inches,is_diabetes,is_heart_failure,is_hypertension,is_renal_failure,BMI,BMI_Category,primary_city,area_codes,COUNTY_NAME,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,COUNTYFIPS,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ANY,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_CIVIL_NONINST_POP_POV,ACS_TOT_CIVIL_POP_POV,ACS_TOT_POP_POV
0,GGGGGGG99DXUNNS,2017-11-29,4BGLS,20709,77,Female,NaN,NaN,NaN,NaN,NaN,None,NaN,PT,NaN,56,0,679120,I69.354,I69.311,F03.90,I10.,H35.3290,Z91.81,NaN,NaN,0,0,0,0,0,Underweight,Austin,"512, 737",Travis,1290188.0,562488.0,1224251.0,94.89,65937.0,5.11,48453,32.074345,22.720897,18.759759,15.975069,10.125310,1.126621,73.554724,43.738517,32.210448,21.982241,5.364069,77.367655,88.875172,6.101690,82.169241,9.295000,0.120241,88.995310,3.084621,3.860310,6.885931,2.473000,0.005034,85.658207,2.725345,5.117103,90.312759,5.603414,68.051034,0.605414,5.587552,26.428103,31.441345,8.488448,20.070172,28.869621,18.399828,6.166552,14.115345,59.224138,9.056379,25.322103,47.800931,17.476414,15.557483,6.956862,2.961000,8.280103,7.701241,6.646034,4.280931,11.512966,3.100828,10.822793,73.126034,12.605586,5.032621,10.705379,19.303103,14.320379,11.069241,2.068966,14.276517,9.661000,9.426172,4223.255172,3299.406897,4225.820690
1,GGGGGGG99GWNzUW,2017-02-08,1AHKS,696175,74,Female,0.0,0.0,1.0,0.0,0.0,None,0.0,RN,NaN,314,0,747199,I25.10,I25.83,I50.42,M12.89,M54.30,R26.89,146.0,65.0,0,0,0,0,25,Overweight,Houston,"281, 346, 713, 832",Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338
2,GGGGGGG99NWze9G,2017-10-16,1CHKT,83192,75,Male,0.0,0.0,0.0,0.0,0.0,None,1.0,RN,NaN,56,0,679372,L03.114,I11.0,I50.9,J44.9,I25.10,F17.210,197.0,66.0,0,0,0,0,32,Obese-Class1,Texarkana,"430, 870, 903",Bowie,92893.0,39536.0,57646.0,62.06,35247.0,37.94,48037,13.153846,33.281923,7.370769,35.667308,10.525000,0.661154,53.806923,20.079231,41.513846,38.408077,0.795769,54.897692,71.698077,7.666923,61.746154,13.377692,0.351154,72.049615,3.468846,20.300000,24.481154,1.093462,0.120000,63.823462,4.888077,16.515769,72.741538,11.768846,33.311538,0.359231,14.919231,39.696923,26.125769,26.372308,43.655769,30.853077,32.633846,12.482308,21.652692,111.923077,13.427692,31.598077,30.037692,24.936923,25.905000,12.053462,7.215769,11.689615,12.323077,8.606538,3.174615,16.306538,5.153846,15.103462,61.638077,18.105000,2.220769,3.846154,19.703462,11.421923,22.495000,3.846154,6.445769,15.411538,14.380769,3375.500000,2529.307692,3376.115385
3,GGGGGGG99NeDX99,2017-03-01,4BGKS,1472419,72,Female,NaN,NaN,NaN,NaN,NaN,None,NaN,RN,NaN,397,0,747517,E11.22,I13.2,I50.9,N18.6,I48.2,D63.1,NaN,NaN,0,0,0,0,0,Underweight,Houston,"281, 346, 713, 832",Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338
4,GGGGGGG99S9eeNG,2017-04-06,3BGKS,3396341,74,Female,NaN,NaN,NaN,NaN,NaN,None,NaN,RN,NaN,837,0,747909,E11.9,I10.,M10.9,E78.5,E03.9,M19.012,NaN,NaN,0,0,0,0,0,Underweight,Alice,361,Jim Wells,38891.0,16156.0,19413.0,49.92,19478.0,50.08,48249,11.921818,27.913636,4.406364,34.315455,21.446364,0.795455,44.239091,17.598182,32.280909,50.120000,7.776364,47.620000,66.845455,13.958182,48.866364,10.177273,0.288182,67.133636,1.754545,23.666364,31.111818,2.650000,0.000000,63.172727,13.531818,13.952727,61.383636,9.549091,29.725455,0.713636,18.581818,33.286364,47.649091,15.755455,27.504545,19.467273,31.725455,8.910909,22.246364,191.909091,14.171818,30.250000,27.308182,28.270909,32.624545,17.028182,8.758182,9.075455,17.190909,11.914545,2.070000,16.760909,3.427273,18.450000,57.556364,20.564545,20.255455,0.000000,11.363636,21.660000,11.477273,0.000000,16.250000,10.021818,12.255455,3662.454545,2639.727273,3662.454545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444767,GGGGGGXzezDW9WN,2017-09-14,2AGKS,372944,66,Male,0.0,0.0,0.0,1.0,0.0,None,0.0,RN,NaN,40,0,677949,Z91.81,I10.,R73.03,K70.30,M62.81,None,NaN,NaN,0,0,0,0,0,Underweight,Dallas,"214, 469, 945, 972",Dallas,2613539.0,1038656.0,2598426.0,99.42,15113.0,0.58,48113,20.988509,24.817189,12.637981,22.061491,19.339860,1.534286,58.443525,33.383649,36.730280,27.867314,9.999193,68.165373,84.583385,5.061848,77.982236,13.287640,0.162034,84.745295,2.575031,7.577065,12.369208,6.133929,0.024783,75.187655,3.187360,6.559503,86.710947,11.674224,59.402516,0.650342,8.581366,34.603882,40.321879,10.455031,23.291460,28.347873,21.821537,7.568851,20.811817,102.635093,12.766584,29.797236,35.208773,21.916988,19.324953,10.620823,4.563339,8.240140,11.187516,5.930932,4.398804,11.923835,5.332578,15.425699,65.013183,13.918214,5.883696,9.716553,15.984161,15.772283,12.433401,0.359363,14.423183,10.034922,7.618354,4024.355590,2969.970497,4025.928571
444768,GGGGGGXzezWGS9W,2017-08-22,None,303296,35,Male,NaN,NaN,NaN,NaN,NaN,None,NaN,RN,NaN,55,0,677874,None,None,None,None,None,None,NaN,NaN,0,0,0,0,0,Underweight,League City,"281, 346, 713, 832",Galveston,350682.0,156191.0,336429.0,95.94,14253.0,4.06,48167,20.483039,32.591961,10.837941,24.593137,10.512647,1.558039,63.914314,30.930686,39.571373,28.518431,2.765392,69.815686,87.449412,4.611765,82.149706,13.574216,0.298333,87.747647,1.892843,6.432843,9.379020,2.123725,0.082745,78.392353,3.136667,7.348529,87.467255,8.878039,64.563137,0.635882,9.173137,29.431275,37.105784,12.857745,26.506863,26.584412,27.902843,10.116667,16.831176,62.872549,10.147157,25.128039,46.414804,17.328922,20.880000,10.722941,4.060392,7.508627,11.163627,4.949216,3.694020,11.166176,3.870588,12.067843,71.593824,11.486176,4.224314,9.499902,12.590686,13.846471,11.553824,0.980392,9.385392,9.711569,7.017451,3241.784314,2448.303922,3245.901961
444769,GGGGGGXzezXDeDW,2017-12-01,1CGKU,639032,61,Male,0.0,0.0,1.0,0.0,0.0,None,0.0,RN,NaN,0,0,747092,S71.101A,S81.801D,I10.,B18.2,K70.30,I73.9,140.0,68.0,0,0,0,0,22,Normal weight,Dallas,"214, 469, 945, 972",Dallas,2613539.0,1038656.0,2598426.0,99.42,15113.0,0.58,48113,20.988509,24.817189,12.637981,22.061491,19.339860,1.534286,58.443525,33.383649,36.730280,27.867314,9.999193,68.165373,84.583385,5.061848,77.982236,13.287640,0.162034,84.745295,2.575031,7.577065,12.369208,6.133929,0.024783,75.187655,3.187360,6.559503,86.710947,11.674224,59.402516,0.650342,8.581366,34.603882,40.321879,10.455031,23.291460,28.347873,21.821537,7.568851,20.811817,102.635093,12.766584,29.797236,35.208773,21.916988,19.324953,10.620823,4.563339,8.240140,11.187516,5.930932,4.398804,11.923835,5.332578,15.425699,65.013183,13.918214,5.883696,9.716553,15.984161,15.772283,12.433401,0.359363,14.423183,10.034922,7.618354,4024.355590,2969.970497,4025.928571
444770,GGGGGGXzzGe9XWN,2017-05-06,1BHKV,376749,66,Male,0.0,0.0,0.0,1.0,0.0,None,0.0,RN,NaN,55,0,679522,S21.102D,I10.,Z85.028,None,None,None,175.0,73.0,0,0,0,0,24,Normal weight,El Paso,915,El Paso,865657.0,317894.0,830826.0,95.98,34831.0,4.02,48141,14.964521,31.078777,7.088936,23.227074,23.108511,1.812500,53.132660,26.251755,43.925106,29.290745,24.270532,60.546277,80.876436,5.884840,74.297660,16.754734,0.158138,81.034681,2.948670,11.240904,15.484894,1.536489,0.007979,67.868777,2.977181,7.637979,83.073883,13.922447,55.598351,0.738032,12.805745,36.121330,50.884521,8.389734,30.619734,23.578191,27.837713,8.995053,24.909468,142.569149,16.209521,30.811809,20.171383,32.275532,32.848245,21.728936,11.547447,9.945638,22.284787,7.939309,4.297926,18.836436,6.865213,20.067394,51.200319,21.334521,8.853830,7.861755,14.174787,22.245638,20.189415,1.595745,23.420585,15.349096,8.230479,4310.936170,3111.734043,4370.893617
444771,GGGGGGXzzNUeN9X,2017-12-22,1CGPV,297214,64,Female,0.0,0.0,0.0,1.0,0.0,None,0.0,RN,NaN,0,0,457954,A41.9,N39.0,I49.9,I10.,I50.9,E11.9,246.0,60.0,0,0,0,0,49,Obese-Class3,Houston,"281, 346, 713, 832",Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338

In [29]:
df_merged.columns

Index(['Beneficiary_ID', 'Assessment_Effective_Date', 'Submitted_HIPPS_Code',
       'Facility_Internal_ID', 'Age', 'Gender',
       'American_Indian_or_Alaska_Native', 'Asian',
       'Black_or_African_American', 'Hispanic_or_Latino',
       ...
       'ACS_PCT_POV_BLACK', 'ACS_PCT_POV_HISPANIC', 'ACS_PCT_POV_MULTI',
       'ACS_PCT_POV_NHPI', 'ACS_PCT_POV_OTHER', 'ACS_PCT_POV_WHITE',
       'ACS_PCT_VET_POV_18_64', 'ACS_TOT_CIVIL_NONINST_POP_POV',
       'ACS_TOT_CIVIL_POP_POV', 'ACS_TOT_POP_POV'],
      dtype='object', length=110)

In [ ]:
df_merged.to_csv("data/texasDashboardData.csv", index=False)

In [ ]:
missing_percentage = (df_merged.isna().sum() / len(df_merged)) * 100

# Convert to DataFrame and sort by missing percentage
missing_percentage = missing_percentage.sort_values(ascending=False).to_frame('Missing Percentage')

# Plotting the missing percentage
plt.figure(figsize=(40, 6))
sns.barplot(x=missing_percentage.index, y=missing_percentage['Missing Percentage'])
plt.xticks(rotation=90, fontsize=10)
plt.ylabel('Percentage of Missing Values (%)')
plt.xlabel('Columns')
plt.title('Percentage of Missing Values Per Column')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

In [ ]:
spark.stop()